# -*- coding: utf8 -*-

"""Lookup tables used in the Researcher Format transformation."""

# Import required modules
# These should all be contained in the standard library
from collections import OrderedDict

__author__ = 'Victoria Morris'
__license__ = 'MIT License'
__version__ = '1.0.0'
__status__ = '4 - Beta Development'

# ====================
#    Lookup tables
# ====================

TYPES = OrderedDict({
    '032': 'Fonds',
    '033': 'SubFonds',
    '034': 'SubSubFonds',
    '035': 'SubSubSubFonds',
    '036': 'Series',
    '037': 'SubSeries',
    '038': 'SubSubSeries',
    '039': 'SubSubSubSeries',
    '040': 'File',
    '041': 'Item',
    '042': 'SubItem',
    '043': 'SubSubItem',
    '044': 'SubSubSubItem',
    '045': 'Corporation',
    '046': 'Family',
    '047': 'Person',
    '048': 'Place',
    '049': 'Subject',
})

SOURCES = OrderedDict({
    'B': 'BNB',
    'E': 'ESTC',
    'M': 'MainCat',
})

PLACES_ENGLAND = ['Accrington', 'Aldermaston', 'Alfreton', 'Alnwick', 'Alton', 'Ambleside', 'Andover', 'Arundel',
                  'Aylesbury', 'Aylesford', 'Bacup', 'Bakewell', 'Banbury', 'Barnoldswick', 'Barnsley', 'Barnstaple',
                  'Barrow-in-Furness', 'Basildon', 'Basingstoke', 'Bath', 'Batley', 'Benfleet', 'Berkhamsted',
                  'Berwick', 'Bexhill', 'Biddulph', 'Biggleswade', 'Bingley', 'Birkenhead', 'Bishop Auckland',
                  'Bishop\'s Stortford', 'Blackburn', 'Blackpool', 'Bournemouth', 'Bowness-On-Windermere', 'Bracknell',
                  'Bradford', 'Braintree', 'Bridlington', 'Brighton', 'Bristol', 'Burnham-on-Sea', 'Burnley', 'Byfleet',
                  'Cannock', 'Canterbury', 'Carlisle', 'Chatham', 'Chelmsford', 'Chelsea', 'Chepstow', 'Chertsey',
                  'Chester', 'Chesterfield', 'Chichester', 'Chippenham', 'Chorley', 'Clacton-on-Sea', 'Cleethorpes',
                  'Clitheroe', 'Cockermouth', 'Colchester', 'Colne', 'Congleton', 'Consett', 'Coventry', 'Crediton',
                  'Dalton-in-Furness', 'Derby', 'Devizes', 'Dewsbury', 'Douglas', 'Driffield', 'Dudley', 'Dunstable',
                  'Egham', 'Ellesmere', 'Enfield', 'Epping', 'Epsom', 'Epworth', 'Evesham', 'Exeter', 'Exmouth',
                  'Fakenham', 'Falmouth', 'Farnborough', 'Farnham', 'Faversham', 'Felixstowe', 'Fleetwood', 'Frodsham',
                  'Frome', 'Gainsborough', 'Garstang', 'Gateshead', 'Gloucester', 'Godalming', 'Goole', 'Gosport',
                  'Grantham', 'Gravesend', 'Grimsby', 'Hammersmith', 'Harlow', 'Harpenden', 'Harrogate', 'Hartford',
                  'Hartlepool', 'Harwich', 'Haslemere', 'Haslingden', 'Haverhill', 'Heckmondwike', 'Hemel Hempstead',
                  'Hereford', 'Hexham', 'Hitchin', 'Hoddesdon', 'Honiton', 'Horsforth', 'Huddersfield', 'Hull',
                  'Hunstanton', 'Ilfracombe', 'Ilkley', 'Ipswich', 'Keighley', 'Kendal', 'Knaresborough', 'Knutsford',
                  'Launceston', 'Leamington', 'Leeds', 'Letchworth', 'Lewes', 'Lichfield', 'Liskeard', 'Littlehampton',
                  'Liverpool', 'London', 'Loughborough', 'Lowestoft', 'Ludlow', 'Luton', 'Lymington', 'Macclesfield',
                  'Maidenhead', 'Maidstone', 'Marlborough', 'Maryport', 'Melton Mowbray', 'Middlesbrough', 'Morecambe',
                  'Morpeth', 'Newark', 'Newcastle upon Tyne', 'Newcastle-Upon-Tyne', 'Newington-Causey', 'Newmarket',
                  'Newquay', 'Newry', 'Newton-le-Willows', 'Normanton', 'Northallerton', 'Northampton', 'Northwich',
                  'Norwich', 'Nottingham', 'Nuneaton', 'Ormskirk', 'Otley', 'Paignton', 'Penistone', 'Penrith',
                  'Penryn', 'Penzance', 'Peterborough', 'Petersfield', 'Pontefract', 'Portsmouth', 'Preston',
                  'Ramsgate', 'Rawtenstall', 'Reading', 'Redruth', 'Reigate', 'Richmond', 'Rickmansworth', 'Ripley',
                  'Ripon', 'Risley', 'Rotherham', 'Royston', 'Rugby', 'Rugeley', 'Runcorn', 'Saffron Walden',
                  'Saint Albans', 'Saltburn-by-the-Sea', 'Scarborough', 'Scunthorpe', 'Seaham', 'Selby', 'Sevenoaks',
                  'Shaftesbury', 'Sheerness', 'Sheffield', 'Shoreham-by-Sea', 'Shrewsbury', 'Sidmouth', 'Sittingbourne',
                  'Skegness', 'Skelmersdale', 'Skipton', 'Sleaford', 'Slough', 'Solihull', 'Southampton',
                  'Southend-on-Sea', 'Southport', 'Spalding', 'Spenborough', 'Stafford', 'Staines', 'Stamford',
                  'Stevenage', 'Stockport', 'Stockton-on-Tees', 'Stoke-on-Trent', 'Stourbridge', 'Stourport',
                  'Stowmarket', 'Sudbury', 'Sunderland', 'Sutton Coldfield', 'Swaffham', 'Swanage', 'Swanley',
                  'Swindon', 'Tadcaster', 'Tamworth', 'Taunton', 'Teignmouth', 'Tenby', 'Thetford', 'Thirsk', 'Tipton',
                  'Tiverton', 'Todmorden', 'Tonbridge', 'Torquay', 'Totnes', 'Trowbridge', 'Truro', 'Tunbridge Wells',
                  'Tynemouth', 'Ulverston', 'Uttoxeter', 'Wakefield', 'Wallasey', 'Wallsend', 'Walsall',
                  'Waltham Abbey', 'Walton on the Naze', 'Walton-on-Thames', 'Warrington', 'Warwick', 'Wednesbury',
                  'West Bromwich', 'Westminster', 'Weston-super-Mare', 'Wetherby', 'Weymouth', 'Whitehaven',
                  'Whitstable', 'Widnes', 'Wigton', 'Wilmslow', 'Wimborne', 'Wincanton', 'Winchester', 'Windermere',
                  'Wisbeach', 'Wishaw', 'Withernsea', 'Woking', 'Wokingham', 'Wolverhampton', 'Wolverton', 'Workington',
                  'Worthing', 'Wymondham', 'Yarmouth', 'Yeovil']

PLACES_IRELAND = ['Ballyshannon', 'Carlow', 'Carrick-on-Shannon', 'Clonmel', 'Drogheda', 'Dublin', 'Dundalk',
                  'Enniscorthy', 'Limerick', 'Sligo', 'Tralee', 'Waterford', 'Wicklow']

PLACES_N_IRELAND = ['Armagh', 'Ballymena', 'Ballymoney', 'Ballynahinch', 'Carrickfergus', 'Belfast', 'Derry',
                    'Enniskillen', 'Omagh']

PLACES_SCOTLAND = ['Aberdeen', 'Airdrie', 'Alloa', 'Ayr', 'Broxbourn', 'Campbeltown', 'Clydebank', 'Cowdenbeath',
                   'Cumbernauld', 'Cupar', 'Dingwall', 'Dumbarton', 'Dumfries', 'Dundee', 'Dunfermline', 'Edinburgh',
                   'Elgin', 'Falkirk', 'Forfar', 'Galashiels', 'Glasgow', 'Glencoe', 'Greenock', 'Hawick',
                   'Helensburgh', 'Inverness', 'Kelso', 'Kilmarnock', 'Kirkcaldy', 'Kirkintilloch', 'Kirkwall',
                   'Kirriemuir', 'Leith', 'Linlithgow', 'Montrose', 'Motherwell', 'Musselburgh', 'Nairn', 'Oban',
                   'Paisley', 'Peebles', 'Selkirk', 'Stirling', 'Stranraer']

PLACES_WALES = ['Aberavon', 'Aberdare', 'Abergavenny', 'Abergele', 'Abersychan', 'Abertillery', 'Aberystwyth', 'Bala',
                'Blaenau Ffestiniog', 'Blaenavon', 'Bangor', 'Brecon', 'Caernarvon', 'Caerphilly', 'Cardiff',
                'Carmarthen', 'Colwyn Bay', 'Denbigh', 'Haverfordwest', 'Fishguard', 'Llandudno', 'Llanelli',
                'Llangollen', 'Llanidloes', 'Llantrisant', 'Merthyr Tydfil', 'Monmouth', 'Oswestry', 'Pembroke',
                'Pontypool', 'Pontypridd', 'Pontypridd', 'Prestatyn', 'Pwllheli', 'Rhondda', 'Rhyl', 'Swansea',
                'Tredegar', 'Welshpool', 'Wrexham']

PLACES_US = ['Albany', 'Baltimore', 'Buffalo', 'Charlestown', 'Chicago', 'Cincinnati', 'Dallas', 'Des Moines',
             'Fort Madison', 'Fort Scott', 'Fort Smith', 'Fort Worth', 'Grand Forks', 'Grand Haven', 'Grand Rapids',
             'Granite City', 'Grass Valley', 'Guntersville', 'Hoboken', 'Hollidaysburg', 'Holly Springs', 'Houston',
             'Hudson', 'Ithaca', 'Jackson', 'Jacksonville', 'Janesville', 'Jefferson', 'Jersey City', 'Kansas City',
             'Knoxville', 'Little Rock', 'Los Angeles', 'Louisville', 'Lynchburg', 'Mackinaw City', 'Madison',
             'Marysville', 'Memphis', 'Miami', 'Milwaukee', 'Minneapolis', 'Nashville', 'New Bedford', 'New Haven',
             'New Orleans', 'New York', 'Omaha', 'Oregon City', 'Parkersburg', 'Paterson', 'Perrysburg', 'Pittsburgh',
             'Pottsville', 'Red Bluff', 'Rockville', 'Salt Lake City', 'San Diego', 'Savannah', 'Southern Pines',
             'Tallahassee', 'Union Springs', 'Urbana', 'Vicksburg', 'Virginia City', 'Warrensburg', 'Washington',
             'Waynesville', 'Whitewater', 'Williamsburg', 'Woodstock']

PLACES_OTHER = ['Aabenraa', 'Aachen', 'Aalborg', 'Aalen', 'Aalten', 'Aarau', 'Aarhus', 'Abidjan', 'Accra', 'Adelaide',
                'Aldershot', 'Alexandria', 'Algiers', 'Allahabad', 'Allentown', 'Amersham', 'Ammanford', 'Ampthill',
                'Amsterdam', 'Antwerp', 'Apeldoorn', 'Argostolion', 'Armidale', 'Arnhem', 'Ashford', 'Ashington',
                'Ashkhabad', 'Ashtabula', 'Atchison', 'Athens', 'Athlone', 'Atlanta', 'Auckland', 'Augsburg', 'Augusta',
                'Axminster', 'Baghdad', 'Ballarat', 'Ballina', 'Ballinasloe', 'Ballinrobe', 'Bangalore', 'Bangkok',
                'Banjul', 'Barberton', 'Barcelona', 'Bari', 'Basseterre', 'Bebington', 'Beith', 'Bendigo', 'Bendorf',
                'Berlin', 'Bethesda', 'Bethlehem', 'Beverley', 'Bideford', 'Bilbao', 'Billericay', 'Billingham',
                'Bilston', 'Birkenfeld', 'Birmingham', 'Blackwood', 'Blandford', 'Blantyre', 'Blaydon', 'Bletchley',
                'Bloemfontein', 'Blyth', 'Bodmin', 'Bologna', 'Bombay', 'Bonnyrigg', 'Bordeaux', 'Borehamwood',
                'Boulogne', 'Brakpan', 'Brandon', 'Bratislava', 'Breda', 'Bregenz', 'Bremen', 'Brentwood', 'Bridgend',
                'Bridgeport', 'Bridgetown', 'Bridgnorth', 'Bridgwater', 'Brigg', 'Brighouse', 'Brisbane', 'Brixham',
                'Brno', 'Broadstairs', 'Brunswick', 'Brussels', 'Buckingham', 'Budapest', 'Bulawayo', 'Bungay',
                'Burlington', 'Cairo', 'Calcutta', 'Calgary', 'Camberley', 'Camborne', 'Cambridge', 'Caracas',
                'Cardigan', 'Casablanca', 'Castlebar', 'Castleford', 'Castries', 'Catania', 'Catanzaro', 'Caterham',
                'Charleroi', 'Charleston', 'Charlottetown', 'Chemnitz', 'Cherbourg', 'Chernovtsy', 'Chesham',
                'Christchurch', 'Clermont-Ferrand', 'Clevedon', 'Cleveland', 'Clinton', 'Coalville', 'Coatbridge',
                'Cologne', 'Colombo', 'Coolgardie', 'Copenhagen', 'Cork', 'Corwen', 'Cosenza', 'Cracow', 'Cradock',
                'Crawley', 'Crewe', 'Crowborough', 'Damascus', 'Danville', 'Dar-es-Salaam', 'Darlington', 'Darmstadt',
                'Dartford', 'Dartmouth', 'Delft', 'Delhi', 'Detmold', 'Detroit', 'Deventer', 'Dinnington', 'Doncaster',
                'Dorchester', 'Dordrecht', 'Dorking', 'Dortmund', 'Douglas', 'Dresden', 'Dromore', 'Dunedin',
                'Dungannon', 'Durban', 'Durham', 'Eastbourne', 'Eastleigh', 'Edenbridge', 'Edmonton', 'Eindhoven',
                'Enschede', 'Essen', 'Evansville', 'Failsworth', 'Fleet', 'Flemington', 'Flensburg', 'Florence',
                'Flushing', 'Folkestone', 'Freehold', 'Freeport', 'Freetown', 'Fremantle', 'Geneva', 'Georgetown',
                'Gillingham', 'Gisborne', 'Grahamstown', 'Groningen', 'Guildford', 'Haarlem', 'Haddington', 'Hadleigh',
                'Halesworth', 'Halifax', 'Hamburg', 'Hamilton', 'Hannover', 'Hanover', 'Harare', 'Hastings', 'Havana',
                'Havant', 'Heidelberg', 'Heidenheim', 'Helsinki', 'Hermoupolis', 'Hertford', 'Hertogenbosch',
                'Hildesheim', 'Hinckley', 'Hobart', 'Holyhead', 'Holywell', 'Honiara', 'Honolulu', 'Horncastle',
                'Hornsea', 'Horsetown', 'Horsham', 'Hove', 'Hoylake', 'Huntingdon', 'Huntington', 'Hythe', 'Ibadan',
                'Indianapolis', 'Innsbruck', 'Invercargill', 'Istanbul', 'Jakarta', 'Jamestown', 'Jeddah',
                'Johannesburg', 'Johnstone', 'Karachi', 'Karlsruhe', 'Kartuzy', 'Kassel', 'Katowice', 'Keene', 'Kells',
                'Kiel', 'Kiev', 'Kingsbridge', 'Kingston', 'Kingstown', 'Koblenz', 'Kota Kinabalu', 'Krugersdorp',
                'Kuala Lumpur', 'Lagos', 'Lahore', 'Lancaster', 'Leatherhead', 'Leeuwarden', 'Leicester', 'Leiden',
                'Leipzig', 'Lexington', 'Leyland', 'Lille', 'Lima', 'Limoges', 'Lincoln', 'Lisbon', 'Lisburn',
                'Loughton', 'Lyons', 'Maastricht', 'Mablethorpe', 'Madras', 'Madrid', 'Mafikeng', 'Magdeburg',
                'Maghull', 'Malmesbury', 'Manchester', 'Manila', 'Mannheim', 'Margate', 'Marseilles', 'Maryborough',
                'Mbabane', 'Melbourne', 'Mexborough', 'Mexico City', 'Milan', 'Minsk', 'Monrovia', 'Montevideo',
                'Montpellier', 'Montreal', 'Moscow', 'Mullingar', 'Munich', 'Nagasaki', 'Nairobi', 'Naples', 'Nassau',
                'Nemaha', 'Nenagh', 'Newbury', 'Newcastle', 'Newtown', 'Nicosia', 'Nijmegen', 'Nuremberg', 'Offenbach',
                'Offenburg', 'Oldenburg', 'Olsztyn', 'Oslo', 'Oxford', 'Painswick', 'Palermo', 'Pamplona',
                'Panama City', 'Paris', 'Penarth', 'Perth', 'Philadelphia', 'Pietermaritzburg', 'Plymouth', 'Portland',
                'Potchefstroom', 'Prague', 'Pretoria', 'Quebec', 'Rangoon', 'Rawmarsh', 'Rayleigh', 'Regina', 'Riga',
                'Ringwood', 'Rochester', 'Rockhampton', 'Rome', 'Romsey', 'Roscommon', 'Roseau', 'Rothesay', 'Rothwell',
                'Rotterdam', 'Sacramento', 'Saint Petersburg', 'Salerno', 'Salisbury', 'Salonica', 'San Salvador',
                'Sandakan', 'Sandbach', 'Sandbank', 'Sandgate', 'Sandhurst', 'Santiago', 'Santo Domingo', 'Shanghai',
                'Shanklin', 'Sherborne', 'Skibbereen', 'St Helen\'s', 'Stockholm', 'Strabane', 'Stuttgart', 'Sydney',
                'Szczecin', 'Taipei', 'Tallinn', 'Tangier', 'Tbilisi', 'Tegucigalpa', 'The Hague', 'Tokyo', 'Toronto',
                'Toulon', 'Toulouse', 'Trenton', 'Trieste', 'Tullamore', 'Turin', 'Turku', 'Tzaneen', 'Uckfield',
                'Utrecht', 'Valdivia', 'Valencia', 'Valletta', 'Valparaiso', 'Vancouver', 'Venice', 'Ventnor', 'Vienna',
                'Vilnius', 'Wanganui', 'Warminster', 'Warsaw', 'Watford', 'Wellington', 'Wexford', 'Whitchurch',
                'Whiteabbey', 'Wickford', 'Wiesbaden', 'Wilhelmshaven', 'Williamsport', 'Windhoek', 'Windsor',
                'Winnipeg', 'Worcester', 'Wuppertal', 'Yokohama', 'Zagreb', 'Zevenbergen', 'Zurich', 'Zutphen',
                'Zwolle', ]

PLACES = list(set().union(PLACES_ENGLAND, PLACES_IRELAND, PLACES_N_IRELAND, PLACES_SCOTLAND, PLACES_WALES, PLACES_US,
                          PLACES_OTHER))

# Lookup table for MARC fields
marc_fields = {
    '001': 'Control Number',
    '003': 'Control Number Identifier',
    '005': 'Date and Time of Latest Transaction',
    '006': 'Fixed-Length Data Elements - Additional Material Characteristics',
    '007': 'Physical Description Fixed Field',
    '008': 'Fixed Length Data Elements',
    '010': 'Library of Congress Control Number',
    '013': 'Patent Control Information',
    '015': 'National Bibliography Number',
    '016': 'National Bibliographic Agency Control Number',
    '017': 'Copyright or Legal Deposit Number',
    '018': 'Copyright Article-Fee Code',
    '019': 'Legacy Control Number',
    '020': 'International Standard Book Number',
    '022': 'International Standard Serial Number',
    '024': 'Other Standard Identifier',
    '025': 'Overseas Acquisition Number',
    '027': 'Standard Technical Report Number',
    '028': 'Publisher Number',
    '030': 'CODEN Designation',
    '031': 'Musical Incipits Information',
    '032': 'Postal Registration Number',
    '033': 'Date/Time and Place of an Event',
    '034': 'Coded Cartographic Mathematical Data',
    '035': 'System Control Number',
    '036': 'Original Study Number for Computer Data files',
    '037': 'Source of Acquisition',
    '038': 'Record Content Licensor',
    '039': 'National Bibliography Issue Number',
    '040': 'Cataloging Source',
    '041': 'Language Code',
    '042': 'Authentication Code',
    '043': 'Geographic Area Code',
    '044': 'Country of Publishing/Producing Entity Code',
    '045': 'Time Period of Content',
    '046': 'Special Coded Dates',
    '047': 'Form of Musical Composition Code',
    '048': 'Number of Musical Instruments or Voices Code',
    '050': 'Library of Congress Call Number',
    '051': 'Library of Congress Copy, Issue, Offprint Statement',
    '052': 'Geographic Classification',
    '055': 'Classification Numbers Assigned in Canada',
    '060': 'National Library of Medicine Call Number',
    '061': 'National Library of Medicine Copy Statement',
    '066': 'Character Sets Present',
    '070': 'National Agricultural Library Call Number',
    '071': 'National Agricultural Library Copy Statement',
    '072': 'Subject Category Code',
    '074': 'GPO Item Number',
    '080': 'Universal Decimal Classification Number',
    '082': 'Dewey Decimal Classification Number',
    '083': 'Additional Dewey Decimal Classification Number',
    '084': 'Other Classification Number',
    '085': 'Synthesized Classification Number Components',
    '086': 'Government Document Classification Number',
    '088': 'Report Number',
    '091': 'Previous Control Number (Document Supply Conference)',
    '100': 'Main Entry - Personal Name',
    '110': 'Main Entry - Corporate Name',
    '111': 'Main Entry - Meeting Name',
    '130': 'Main Entry - Uniform Title',
    '210': 'Abbreviated Title',
    '222': 'Key Title',
    '240': 'Uniform Title',
    '242': 'Translation of Title by Cataloging Agency',
    '243': 'Collective Uniform Title',
    '245': 'Title Statement',
    '246': 'Varying Form of Title',
    '247': 'Former Title',
    '250': 'Edition Statement',
    '254': 'Musical Presentation Statement',
    '255': 'Cartographic Mathematical Data',
    '256': 'Computer File Characteristics',
    '257': 'Country of Producing Entity',
    '258': 'Philatelic Issue Data',
    '260': 'Publication, Distribution, etc. (Imprint)',
    '263': 'Projected Publication Date',
    '264': 'Production, Publication, Distribution, Manufacture, and Copyright Notice',
    '270': 'Address',
    '300': 'Physical Description',
    '306': 'Playing Time',
    '307': 'Hours, Etc.',
    '310': 'Current Publication Frequency',
    '321': 'Former Publication Frequency',
    '336': 'Content Type',
    '337': 'Media Type',
    '338': 'Carrier Type',
    '340': 'Physical Medium',
    '342': 'Geospatial Reference Data',
    '343': 'Planar Coordinate Data',
    '344': 'Sound Characteristics',
    '345': 'Projection Characteristics of Moving Image',
    '346': 'Video Characteristics',
    '347': 'Digital File Characteristics',
    '348': 'Format of Notated Music',
    '351': 'Organization and Arrangement of Materials',
    '352': 'Digital Graphic Representation',
    '355': 'Security Classification Control',
    '357': 'Originator Dissemination Control',
    '362': 'Dates of Publication and/or Sequential Designation',
    '363': 'Normalized Date and Sequential Designation',
    '365': 'Trade Price',
    '366': 'Trade Availability Information',
    '370': 'Associated Place',
    '377': 'Associated Language',
    '380': 'Form of Work',
    '381': 'Other Distinguishing Characteristics of Work or Expression',
    '382': 'Medium of Performance',
    '383': 'Numeric Designation of Musical Work',
    '384': 'Key',
    '385': 'Audience Characteristics',
    '386': 'Creator/Contributor Characteristics',
    '388': 'Time Period of Creation',
    '490': 'Series Statement',
    '500': 'General Note',
    '501': 'With Note',
    '502': 'Dissertation Note',
    '504': 'Bibliography, Etc. Note',
    '505': 'Formatted Contents Note',
    '506': 'Restrictions on Access Note',
    '507': 'Scale Note for Graphic Material',
    '508': 'Creation/Production Credits Note',
    '509': 'Informal Notes',
    '510': 'Citation/References Note',
    '511': 'Participant or Performer Note',
    '513': 'Type of Report and Period Covered Note',
    '514': 'Data Quality Note',
    '515': 'Numbering Peculiarities Note',
    '516': 'Type of Computer File or Data Note',
    '518': 'Date/Time and Place of an Event Note',
    '520': 'Summary, Etc.',
    '521': 'Target Audience Note',
    '522': 'Geographic Coverage Note',
    '524': 'Preferred Citation of Described Materials Note',
    '525': 'Supplement Note',
    '526': 'Study Program Information Note',
    '530': 'Additional Physical Form Available Note',
    '533': 'Reproduction Note',
    '534': 'Original Version Note',
    '535': 'Location of Originals/Duplicates Note',
    '536': 'Funding Information Note',
    '538': 'System Details Note',
    '539': 'Location of Filmed Copy',
    '540': 'Terms Governing Use and Reproduction Note',
    '541': 'Immediate Source of Acquisition Note',
    '542': 'Information Relating to Copyright Status',
    '544': 'Location of Other Archival Materials Note',
    '545': 'Biographical or Historical Data',
    '546': 'Language Note',
    '547': 'Former Title Complexity Note',
    '550': 'Issuing Body Note',
    '552': 'Entity and Attribute Information Note',
    '555': 'Cumulative Index/Finding Aids Note',
    '556': 'Information about Documentation Note',
    '561': 'Ownership and Custodial History',
    '562': 'Copy and Version Identification Note',
    '563': 'Binding Information',
    '565': 'Case File Characteristics Note',
    '567': 'Methodology Note',
    '580': 'Linking Entry Complexity Note',
    '581': 'Publications About Described Materials Note',
    '583': 'Action Note',
    '584': 'Accumulation and Frequency of Use Note',
    '585': 'Exhibitions Note',
    '586': 'Awards Note',
    '588': 'Source of Description Note',
    '590': 'Document Supply General Note',
    '591': 'Document Supply Conference Note',
    '592': 'Collaboration Note',
    '594': 'Reference to Items in Printed Catalogues',
    '595': 'Document Supply Bibliographic History Note',
    '597': 'Editing or Error Message',
    '598': 'Document Supply Selection / Ordering Information',
    '599': 'Notes Relating to an Original',
    '600': 'Subject Added Entry - Personal Name',
    '610': 'Subject Added Entry - Corporate Name',
    '611': 'Subject Added Entry - Meeting Name',
    '630': 'Subject Added Entry - Uniform Title',
    '648': 'Subject Added Entry - Chronological Term',
    '650': 'Subject Added Entry - Topical Term',
    '651': 'Subject Added Entry - Geographic Name',
    '653': 'Index Term-Uncontrolled',
    '654': 'Subject Added Entry-Faceted Topical Terms',
    '655': 'Index Term - Genre/Form',
    '656': 'Index Term - Occupation',
    '657': 'Index Term - Function',
    '658': 'Index Term - Curriculum Objective',
    '662': 'Subject Added Entry-Hierarchical Place Name',
    '690': 'Collection Subset',
    '692': 'Nineteenth Century Subject Series Field',
    '700': 'Added Entry - Personal Name',
    '710': 'Added Entry - Corporate Name',
    '711': 'Added Entry - Meeting Name',
    '720': 'Added Entry - Uncontrolled Name',
    '730': 'Added Entry - Uniform Title',
    '740': 'Added Entry - Uncontrolled Related/Analytical Title',
    '751': 'Added Entry - Geographic Name',
    '752': 'Added Entry - Hierarchical Place Name',
    '753': 'System Details Access to Computer Files',
    '754': 'Added Entry - Taxonomic Identification',
    '760': 'Main Series Entry',
    '762': 'Subseries Entry',
    '765': 'Original Language Entry',
    '767': 'Translation Entry',
    '770': 'Supplement/Special Issue Entry',
    '772': 'Supplement Parent Entry',
    '773': 'Host Item Entry',
    '774': 'Constituent Unit Entry',
    '775': 'Other Edition Entry',
    '776': 'Additional Physical Form Entry',
    '777': 'Issued With Entry',
    '780': 'Preceding Entry',
    '785': 'Succeeding Entry',
    '786': 'Data Source Entry',
    '787': 'Other Relationship Entry',
    '800': 'Series Added Entry - Personal Name',
    '810': 'Series Added Entry - Corporate Name',
    '811': 'Series Added Entry - Meeting Name',
    '830': 'Series Added Entry - Uniform Title',
    '850': 'Holding Institution',
    '852': 'Location',
    '856': 'Electronic Location and Access',
    '859': 'Digital Resource Flag',
    '880': 'Alternate Graphic Representation',
    '882': 'Replacement Record Information',
    '883': 'Machine-generated Metadata Provenance',
    '884': 'Description Conversion Information',
    '886': 'Foreign MARC Information Field',
    '887': 'Non-MARC Information Field',
    '916': 'Authority Control Information',
    '917': 'Production Category',
    '945': 'BL Local Title',
    '950': 'Library of Congress Subject (Cross-Reference)',
    '954': 'Transliteration Statement',
    '955': 'Shelving Location',
    '957': 'Acquisitions Data',
    '958': 'Superseded Shelfmark',
    '959': 'Document Supply Status Flag',
    '960': 'Normalized Place of Publication',
    '961': 'Sheet Index Note',
    '962': 'Colindale Location Flag',
    '963': 'Cambridge University Library Location',
    '964': 'Science Museum Library Location',
    '966': 'Document Supply Acquisitions Indicator',
    '968': 'Record Status Field',
    '970': 'Collection Code',
    '975': 'Insufficient Record Statement',
    '976': 'Non-monographic Conference Indicator',
    '979': 'Negative Shelfmark',
    '980': 'Card Production Indicator',
    '985': 'Cataloguer\'s Note',
    '990': 'Product Information Code',
    '992': 'Stored Search Flag',
    '996': 'Z39.50 SFX Enabler',
    '997': 'Shared Library Message Field',
    'A02': 'Serial Acquisitions System Number',
    # 'ACF':	'Copyright Fee',
    'AQN': 'Acquisitions Notes Field',
    'BGT': 'BGLT (British Grey Literature Team) Report Flag',
    'BUF': 'Batch Upgrade Flag',
    # 'CAT':      'Cataloguer',
    # 'CFI':	'Copyright Fee Information',
    'CNF': 'Document Supply Conference Heading',
    'COR': 'Original Preferred Term',
    'DEL': 'Deleted',
    'DGM': 'Digitised Record Match',
    'DRT': 'Digital Record Type',
    'EST': 'Document Supply ESTAR (Electronic Storage and Retrieval System)',
    'EXP': 'Block Export',
    'FFP': 'Flag For Publication',
    'FIN': 'Finished (Cataloguing)',
    'FMT': 'Format',
    # 'LAS':	'Last CAT Field',
    'LCS': 'Library of Congress Series Statement',
    'LDO': 'LDO (Legal Deposit Office) Information',
    'LDR': 'Leader',
    'LEO': 'LEO (Library Export Operations) Identifier',
    'LET': 'Serials claim letter title',
    'LKR': 'Link',
    'MIS': 'Monograph in Series Flag',
    'MNI': 'Medium Neutral ISSN',
    'MPX': 'Map Leader Data Element',
    'NEG': 'LDO (Legal Deposit Office) Signoff',
    'NID': 'Newspaper Identifier',
    'OBJ': 'Digital Object Field',
    'OHC': 'Original Holding Count',
    'ONS': 'ONIX Subjects',
    'ONX': 'ONIX Un-Mapped Data',
    # 'OWN':      'Access Permission',
    'PLR': 'PRIMO Large Record',
    'RSC': 'Remote Supply Collection',
    'SID': 'Source ID',
    'SRC': 'Source',
    'SSD': 'STI Serials Designation',
    'STA': 'Status',
    # 'SYS':      'Aleph System Number',
    'TOC': 'Document Supply ETOC (Electronic Table of Contents) Flag',
    # 'TCO':	'Unrecognised field',
    'UNO': 'Unencrypted Download ID',
    'UPD': 'Update',
    'VIT': 'Virtual Item',
}

# Lookup table for RDA content types
content_types = {
    'crd': 'Cartographic dataset',
    'cri': 'Cartographic image',
    'crm': 'Cartographic tactile image',
    'crt': 'Cartographic tactile three-dimensional form',
    'crf': 'Cartographic three-dimensional form',
    'cod': 'Computer dataset',
    'cop': 'Computer program',
    'ntv': 'Notated movement',
    'ntm': 'Notated music',
    'prm': 'Performed music',
    'snd': 'Sounds',
    'spw': 'Spoken word',
    'sti': 'Still image',
    'tci': 'Tactile image',
    'tcm': 'Tactile notated music',
    'tcn': 'Tactile notated movement',
    'tct': 'Tactile text',
    'tcf': 'Tactile three-dimensional form',
    'txt': 'Text',
    'tdf': 'Three-dimensional form',
    'tdm': 'Three-dimensional moving image',
    'tdi': 'Two-dimensional moving image',
}

# Lookup table for content types from LDR/06 codes
content_types_ldr = {
    'a': 'Language material',
    'c': 'Notated music',
    'd': 'Manuscript notated music',
    'e': 'Cartographic material',
    'f': 'Manuscript cartographic material',
    'g': 'Projected medium',
    'i': 'Nonmusical sound recording',
    'j': 'Musical sound recording',
    'k': 'Two-dimensional nonprojectable graphic',
    'm': 'Computer file',
    'o': 'Kit',
    'p': 'Mixed materials',
    'r': 'Three-dimensional artifact or naturally occurring object',
    't': 'Manuscript language material',
}

# Lookup table for RDA carrier (material) types
material_types = {
    'sg': 'Audio cartridge',
    'se': 'Audio cylinder',
    'sd': 'Audio disc',
    'si': 'Sound track reel',
    'sq': 'Audio roll',
    'ss': 'Audiocassette',
    'st': 'Audiotape reel',
    'sz': 'Unspecified audio resource',
    'ck': 'Computer card',
    'cb': 'Computer chip cartridge',
    'cd': 'Computer disc',
    'ce': 'Computer disc cartridge',
    'ca': 'Computer tape cartridge',
    'cf': 'Computer tape cassette',
    'ch': 'Computer tape reel',
    'cr': 'Online resource',
    'cz': 'Unspecified computer resource',
    'ha': 'Aperture card',
    'he': 'Microfiche',
    'hf': 'Microfiche cassette',
    'hb': 'Microfilm cartridge',
    'hc': 'Microfilm cassette',
    'hd': 'Microfilm reel',
    'hj': 'Microfilm roll',
    'hh': 'Microfilm slip',
    'hg': 'Microopaque',
    'hz': 'Unspecified microform resource',
    'pp': 'Microscope slide',
    'pz': 'Unspecified microscopic resource',
    'mc': 'Film cartridge',
    'mf': 'Film cassette',
    'mr': 'Film reel',
    'mo': 'Film roll',
    'gd': 'Filmslip',
    'gf': 'Filmstrip',
    'gc': 'Filmstrip cartridge',
    'gt': 'Overhead transparency',
    'gs': 'Slide',
    'mz': 'Unspecified projected image resource',
    'eh': 'Stereograph card',
    'es': 'Stereograph disc',
    'ez': 'Unspecified stereographic resource',
    'no': 'Card',
    'nn': 'Flipchart',
    'na': 'Roll',
    'nb': 'Sheet',
    'nc': 'Volume',
    'nr': 'Object',
    'nz': 'Unspecified unmediated resource',
    'vc': 'Video cartridge',
    'vf': 'Videocassette ',
    'vd': 'Videodisc',
    'vr': 'Videotape reel',
    'vz': 'Unspecified video resource',
    'zu': 'Unspecified resource',
}

# Lookup table for resource types from LDR/07 codes
resource_types = {
    'a': 'Monographic component part',
    'b': 'Serial component part',
    'c': 'Collection',
    'd': 'Subunit',
    'i': 'Integrating resource',
    'm': 'Monograph',
    's': 'Serial',
}

# Lookup table for encoding levels from LDR/17 codes
encoding_levels = {
    ' ': '# - Full level',
    '1': '1 - Full level, material not examined',
    '2': '2 - Less-than-full level, material not examined',
    '3': '3 - Abbreviated level',
    '4': '4 - Core level',
    '5': '5 - Partial (preliminary) level',
    '7': '7 - Minimal level',
    '8': '8 - Prepublication level',
    'u': 'u - Unknown',
    'z': 'z - Not applicable',
}

# Lookup table for target audience from 008/22 codes
audiences = {
    'a': 'Preschool',
    'b': 'Primary',
    'c': 'Pre-adolescent',
    'd': 'Adolescent',
    'e': 'Adult',
    'f': 'Specialized',
    'g': 'General',
    'j': 'Juvenile',
}

# Lookup table for literary form from 008/33 codes
literary_forms = {
    '0': 'Not fiction',
    '1': 'Fiction',
    'd': 'Dramas',
    'e': 'Essays',
    'f': 'Novels',
    'h': 'Humor, satires, etc.',
    'i': 'Letters',
    'j': 'Short stories',
    'm': 'Mixed forms',
    'p': 'Poetry',
    's': 'Speeches',
}

# Lookup table for MARC relator codes
relators = {
    'abr': 'abridger',
    'acp': 'art copyist',
    'act': 'actor',
    'adi': 'art director',
    'adp': 'adapter',
    'aft': 'author of afterword or colophon',
    'anl': 'analyst',
    'anm': 'animator',
    'ann': 'annotator',
    'ant': 'bibliographic antecedent',
    'ape': 'appellee',
    'apl': 'appellant',
    'app': 'applicant',
    'aqt': 'author in quotations or text abstracts',
    'arc': 'architect',
    'ard': 'artistic director',
    'arr': 'arranger',
    'art': 'artist',
    'asg': 'assignee',
    'asn': 'associated name',
    'ato': 'autographer',
    'att': 'attributed name',
    'auc': 'auctioneer',
    'aud': 'author of dialog',
    'aui': 'author of introduction',
    'aus': 'screenwriter',
    'aut': 'author',
    'bdd': 'binding designer',
    'bjd': 'bookjacket designer',
    'bkd': 'book designer',
    'bkp': 'book producer',
    'blw': 'blurb writer',
    'bnd': 'binder',
    'bpd': 'bookplate designer',
    'brd': 'broadcaster',
    'brl': 'braille embosser',
    'bsl': 'bookseller',
    'cas': 'caster',
    'ccp': 'conceptor',
    'chr': 'choreographer',
    'clb': 'collaborator',
    'cli': 'client',
    'cll': 'calligrapher',
    'clr': 'colorist',
    'clt': 'collotyper',
    'cmm': 'commentator',
    'cmp': 'composer',
    'cmt': 'compositor',
    'cnd': 'conductor',
    'cng': 'cinematographer',
    'cns': 'censor',
    'coe': 'contestant-appellee',
    'col': 'collector',
    'com': 'compiler',
    'con': 'conservator',
    'cor': 'collection registrar',
    'cos': 'contestant',
    'cot': 'contestant-appellant',
    'cou': 'court governed',
    'cov': 'cover designer',
    'cpc': 'copyright claimant',
    'cpe': 'complainant-appellee',
    'cph': 'copyright holder',
    'cpl': 'complainant',
    'cpt': 'complainant-appellant',
    'cre': 'creator',
    'crp': 'correspondent',
    'crr': 'corrector',
    'crt': 'court reporter',
    'csl': 'consultant',
    'csp': 'consultant to a project',
    'cst': 'costume designer',
    'ctb': 'contributor',
    'cte': 'contestee-appellee',
    'ctg': 'cartographer',
    'ctr': 'contractor',
    'cts': 'contestee',
    'ctt': 'contestee-appellant',
    'cur': 'curator',
    'cwt': 'commentator for written text',
    'dbp': 'distribution place',
    'dfd': 'defendant',
    'dfe': 'defendant-appellee',
    'dft': 'defendant-appellant',
    'dgg': 'degree granting institution',
    'dgs': 'degree supervisor',
    'dis': 'dissertant',
    'dln': 'delineator',
    'dnc': 'dancer',
    'dnr': 'donor',
    'dpc': 'depicted',
    'dpt': 'depositor',
    'drm': 'draftsman',
    'drt': 'director',
    'dsr': 'designer',
    'dst': 'distributor',
    'dtc': 'data contributor',
    'dte': 'dedicatee',
    'dtm': 'data manager',
    'dto': 'dedicator',
    'dub': 'dubious author',
    'edc': 'editor of compilation',
    'edm': 'editor of moving image work',
    'eds': 'editor',  # Not a MARC code
    'edt': 'editor',
    'egr': 'engraver',
    'elg': 'electrician',
    'elt': 'electrotyper',
    'eng': 'engineer',
    'enj': 'enacting jurisdiction',
    'etr': 'etcher',
    'evp': 'event place',
    'exp': 'expert',
    'fac': 'facsimilist',
    'fds': 'film distributor',
    'fld': 'field director',
    'flm': 'film editor',
    'fmd': 'film director',
    'fmk': 'filmmaker',
    'fmo': 'former owner',
    'fmp': 'film producer',
    'fnd': 'funder',
    'fpy': 'first party',
    'frg': 'forger',
    'gis': 'geographic information specialist',
    'grt': 'graphic technician',
    'his': 'host institution',
    'hnr': 'honoree',
    'hst': 'host',
    'ill': 'illustrator',
    'ilu': 'illuminator',
    'ins': 'inscriber',
    'inv': 'inventor',
    'isb': 'issuing body',
    'itr': 'instrumentalist',
    'ive': 'interviewee',
    'ivr': 'interviewer',
    'jud': 'judge',
    'jug': 'jurisdiction governed',
    'lbr': 'laboratory',
    'lbt': 'librettist',
    'ldr': 'laboratory director',
    'led': 'lead',
    'lee': 'libelee-appellee',
    'lel': 'libelee',
    'len': 'lender',
    'let': 'libelee-appellant',
    'lgd': 'lighting designer',
    'lie': 'libelant-appellee',
    'lil': 'libelant',
    'lit': 'libelant-appellant',
    'lsa': 'landscape architect',
    'lse': 'licensee',
    'lso': 'licensor',
    'ltg': 'lithographer',
    'lyr': 'lyricist',
    'mcp': 'music copyist',
    'mdc': 'metadata contact',
    'med': 'medium',
    'mfp': 'manufacture place',
    'mfr': 'manufacturer',
    'mod': 'moderator',
    'mon': 'monitor',
    'mrb': 'marbler',
    'mrk': 'markup editor',
    'msd': 'musical director',
    'mte': 'metal-engraver',
    'mtk': 'minute taker',
    'mus': 'musician',
    'nrt': 'narrator',
    'opn': 'opponent',
    'org': 'originator',
    'orm': 'organizer',
    'osp': 'onscreen presenter',
    'oth': 'other',
    'own': 'owner',
    'pan': 'panelist',
    'pat': 'patron',
    'pbd': 'publishing director',
    'pbl': 'publisher',
    'pdr': 'project director',
    'pfr': 'proofreader',
    'pht': 'photographer',
    'plt': 'platemaker',
    'pma': 'permitting agency',
    'pmn': 'production manager',
    'pop': 'printer of plates',
    'ppm': 'papermaker',
    'ppt': 'puppeteer',
    'pra': 'praeses',
    'prc': 'process contact',
    'prd': 'production personnel',
    'pre': 'presenter',
    'prf': 'performer',
    'prg': 'programmer',
    'prm': 'printmaker',
    'prn': 'production company',
    'pro': 'producer',
    'prp': 'production place',
    'prs': 'production designer',
    'prt': 'printer',
    'prv': 'provider',
    'pta': 'patent applicant',
    'pte': 'plaintiff-appellee',
    'ptf': 'plaintiff',
    'pth': 'patent holder',
    'ptt': 'plaintiff-appellant',
    'pup': 'publication place',
    'rbr': 'rubricator',
    'rcd': 'recordist',
    'rce': 'recording engineer',
    'rcp': 'addressee',
    'rdd': 'radio director',
    'red': 'redaktor',
    'ren': 'renderer',
    'res': 'researcher',
    'rev': 'reviewer',
    'rpc': 'radio producer',
    'rps': 'repository',
    'rpt': 'reporter',
    'rpy': 'responsible party',
    'rse': 'respondent-appellee',
    'rsg': 'restager',
    'rsp': 'respondent',
    'rsr': 'restorationist',
    'rst': 'respondent-appellant',
    'rth': 'research team head',
    'rtm': 'research team member',
    'sad': 'scientific advisor',
    'sce': 'scenarist',
    'scl': 'sculptor',
    'scr': 'scribe',
    'sds': 'sound designer',
    'sec': 'secretary',
    'sgd': 'stage director',
    'sgn': 'signer',
    'sht': 'supporting host',
    'sll': 'seller',
    'sng': 'singer',
    'spk': 'speaker',
    'spn': 'sponsor',
    'spy': 'second party',
    'srv': 'surveyor',
    'std': 'set designer',
    'stg': 'setting',
    'stl': 'storyteller',
    'stm': 'stage manager',
    'stn': 'standards body',
    'str': 'stereotyper',
    'tcd': 'technical director',
    'tch': 'teacher',
    'ths': 'thesis advisor',
    'tld': 'television director',
    'tlp': 'television producer',
    'trc': 'transcriber',
    'trl': 'translator',
    'tyd': 'type designer',
    'tyg': 'typographer',
    'uvp': 'university place',
    'vac': 'voice actor',
    'vdg': 'videographer',
    'voc': 'vocalist',
    'wac': 'writer of added commentary',
    'wal': 'writer of added lyrics',
    'wam': 'writer of accompanying material',
    'wat': 'writer of added text',
    'wdc': 'woodcutter',
    'wde': 'wood engraver',
    'win': 'writer of introduction',
    'wit': 'witness',
    'wpr': 'writer of preface',
    'wst': 'writer of supplementary textual content',
}

# Lookup table for country names
# States map to the larger country where possible
countries = {
    'aa': 'Albania',
    'abc': 'Canada',  # Alberta
    'ac': 'Ashmore and Cartier Islands',  # Discontinued
    'aca': 'Australia',  # Australian Capital Territory
    'ae': 'Algeria',
    'af': 'Afghanistan',
    'ag': 'Argentina',
    'ai': 'Armenia (Republic)',
    'air': 'Armenian S.S.R.',  # Discontinued
    'aj': 'Azerbaijan',
    'ajr': 'Azerbaijan S.S.R.',  # Discontinued
    'aku': 'United States of America',  # Alaska
    'alu': 'United States of America',  # Alabama
    'am': 'Anguilla',
    'an': 'Andorra',
    'ao': 'Angola',
    'aq': 'Antigua and Barbuda',
    'aru': 'United States of America',  # Arkansas
    'as': 'American Samoa',
    'at': 'Australia',
    'au': 'Austria',
    'aw': 'Aruba',
    'ay': 'Antarctica',
    'azu': 'United States of America',  # Arizona
    'ba': 'Bahrain',
    'bb': 'Barbados',
    'bcc': 'Canada',  # British Columbia
    'bd': 'Burundi',
    'be': 'Belgium',
    'bf': 'Bahamas',
    'bg': 'Bangladesh',
    'bh': 'Belize',
    'bi': 'British Indian Ocean Territory',
    'bl': 'Brazil',
    'bm': 'Bermuda Islands',
    'bn': 'Bosnia and Hercegovina',
    'bo': 'Bolivia',
    'bp': 'Solomon Islands',
    'br': 'Burma',
    'bs': 'Botswana',
    'bt': 'Bhutan',
    'bu': 'Bulgaria',
    'bv': 'Bouvet Island',
    'bw': 'Belarus',
    'bwr': 'Byelorussian S.S.R.',  # Discontinued
    'bx': 'Brunei',
    'ca': 'Caribbean Netherlands',
    'cau': 'United States of America',  # California
    'cb': 'Cambodia',
    'cc': 'China',
    'cd': 'Chad',
    'ce': 'Sri Lanka',
    'cf': 'Congo (Brazzaville)',
    'cg': 'Congo (Democratic Republic)',
    'ch': 'China (Republic : 1949-)',
    'ci': 'Croatia',
    'cj': 'Cayman Islands',
    'ck': 'Colombia',
    'cl': 'Chile',
    'cm': 'Cameroon',
    'cn': 'Canada',  # Discontinued
    'co': 'Curaçao',
    'cou': 'United States of America',  # Colorado
    'cp': 'Canton and Enderbury Islands',  # Discontinued
    'cq': 'Comoros',
    'cr': 'Costa Rica',
    'cs': 'Czechoslovakia',  # Discontinued
    'ctu': 'United States of America',  # Connecticut
    'cu': 'Cuba',
    'cv': 'Cabo Verde',
    'cw': 'Cook Islands',
    'cx': 'Central African Republic',
    'cy': 'Cyprus',
    'cz': 'Canal Zone',  # Discontinued
    'dcu': 'United States of America',  # District of Columbia
    'deu': 'United States of America',  # Delaware
    'dk': 'Denmark',
    'dm': 'Benin',
    'dq': 'Dominica',
    'dr': 'Dominican Republic',
    'ea': 'Eritrea',
    'ec': 'Ecuador',
    'eg': 'Equatorial Guinea',
    'em': 'Timor-Leste',
    'enk': 'England',
    'er': 'Estonia',
    'err': 'Estonia',  # Discontinued
    'es': 'El Salvador',
    'et': 'Ethiopia',
    'fa': 'Faroe Islands',
    'fg': 'French Guiana',
    'fi': 'Finland',
    'fj': 'Fiji',
    'fk': 'Falkland Islands',
    'flu': 'United States of America',  # Florida
    'fm': 'Micronesia (Federated States)',
    'fp': 'French Polynesia',
    'fr': 'France',
    'fs': 'Terres australes et antarctiques françaises',
    'ft': 'Djibouti',
    'gau': 'United States of America',  # Georgia
    'gb': 'Kiribati',
    'gd': 'Grenada',
    'ge': 'Germany (East)',  # Discontinued
    'gh': 'Ghana',
    'gi': 'Gibraltar',
    'gl': 'Greenland',
    'gm': 'Gambia',
    'gn': 'Gilbert and Ellice Islands',  # Discontinued
    'go': 'Gabon',
    'gp': 'Guadeloupe',
    'gr': 'Greece',
    'gs': 'Georgia (Republic)',
    'gsr': 'Georgian S.S.R.',  # Discontinued
    'gt': 'Guatemala',
    'gu': 'Guam',
    'gv': 'Guinea',
    'gw': 'Germany',
    'gy': 'Guyana',
    'gz': 'Gaza Strip',
    'hiu': 'United States of America',  # Hawaii
    'hk': 'Hong Kong',  # Discontinued
    'hm': 'Heard and McDonald Islands',
    'ho': 'Honduras',
    'ht': 'Haiti',
    'hu': 'Hungary',
    'iau': 'United States of America',  # Iowa
    'ic': 'Iceland',
    'idu': 'United States of America',  # Idaho
    'ie': 'Ireland',
    'ii': 'India',
    'ilu': 'United States of America',  # Illinois
    'inu': 'United States of America',  # Indiana
    'io': 'Indonesia',
    'iq': 'Iraq',
    'ir': 'Iran',
    'is': 'Israel',
    'it': 'Italy',
    'iu': 'Israel-Syria Demilitarized Zones',  # Discontinued
    'iv': 'Côte d\'Ivoire',
    'iw': 'Israel-Jordan Demilitarized Zones',  # Discontinued
    'iy': 'Iraq-Saudi Arabia Neutral Zone',
    'ja': 'Japan',
    'ji': 'Johnston Atoll',
    'jm': 'Jamaica',
    'jn': 'Jan Mayen',  # Discontinued
    'jo': 'Jordan',
    'ke': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kgr': 'Kirghiz S.S.R.',  # Discontinued
    'kn': 'Korea (North)',
    'ko': 'Korea (South)',
    'ksu': 'United States of America',  # Kansas
    'ku': 'Kuwait',
    'kv': 'Kosovo',
    'kyu': 'United States of America',  # Kentucky
    'kz': 'Kazakhstan',
    'kzr': 'Kazakh S.S.R.',  # Discontinued
    'lau': 'United States of America',  # Louisiana
    'lb': 'Liberia',
    'le': 'Lebanon',
    'lh': 'Liechtenstein',
    'li': 'Lithuania',
    'lir': 'Lithuania',  # Discontinued
    'ln': 'Central and Southern Line Islands',  # Discontinued
    'lo': 'Lesotho',
    'ls': 'Laos',
    'lu': 'Luxembourg',
    'lv': 'Latvia',
    'lvr': 'Latvia',  # Discontinued
    'ly': 'Libya',
    'mau': 'United States of America',  # Massachusetts
    'mbc': 'Canada',  # Manitoba
    'mc': 'Monaco',
    'mdu': 'United States of America',  # Maryland
    'meu': 'United States of America',  # Maine
    'mf': 'Mauritius',
    'mg': 'Madagascar',
    'mh': 'Macao',  # Discontinued
    'miu': 'United States of America',  # Michigan
    'mj': 'Montserrat',
    'mk': 'Oman',
    'ml': 'Mali',
    'mm': 'Malta',
    'mnu': 'United States of America',  # Minnesota
    'mo': 'Montenegro',
    'mou': 'United States of America',  # Missouri
    'mp': 'Mongolia',
    'mq': 'Martinique',
    'mr': 'Morocco',
    'msu': 'United States of America',  # Mississippi
    'mtu': 'United States of America',  # Montana
    'mu': 'Mauritania',
    'mv': 'Moldova',
    'mvr': 'Moldavian S.S.R.',  # Discontinued
    'mw': 'Malawi',
    'mx': 'Mexico',
    'my': 'Malaysia',
    'mz': 'Mozambique',
    'na': 'Netherlands Antilles',  # Discontinued
    'nbu': 'United States of America',  # Nebraska
    'ncu': 'United States of America',  # North Carolina
    'ndu': 'United States of America',  # North Dakota
    'ne': 'Netherlands',
    'nfc': 'Canada',  # Newfoundland and Labrador
    'ng': 'Niger',
    'nhu': 'United States of America',  # New Hampshire
    'nik': 'Northern Ireland',
    'nju': 'United States of America',  # New Jersey
    'nkc': 'Canada',  # New Brunswick
    'nl': 'New Caledonia',
    'nm': 'Northern Mariana Islands',  # Discontinued
    'nmu': 'United States of America',  # New Mexico
    'nn': 'Vanuatu',
    'no': 'Norway',
    'np': 'Nepal',
    'nq': 'Nicaragua',
    'nr': 'Nigeria',
    'nsc': 'Canada',  # Nova Scotia
    'ntc': 'Canada',  # Northwest Territories
    'nu': 'Nauru',
    'nuc': 'Canada',  # Nunavut
    'nvu': 'United States of America',  # Nevada
    'nw': 'Northern Mariana Islands',
    'nx': 'Norfolk Island',
    'nyu': 'United States of America',  # New York (State)
    'nz': 'New Zealand',
    'ohu': 'United States of America',  # Ohio
    'oku': 'United States of America',  # Oklahoma
    'onc': 'Canada',  # Ontario
    'oru': 'United States of America',  # Oregon
    'ot': 'Mayotte',
    'pau': 'United States of America',  # Pennsylvania
    'pc': 'Pitcairn Island',
    'pe': 'Peru',
    'pf': 'Paracel Islands',
    'pg': 'Guinea-Bissau',
    'ph': 'Philippines',
    'pic': 'Canada',  # Prince Edward Island
    'pk': 'Pakistan',
    'pl': 'Poland',
    'pn': 'Panama',
    'po': 'Portugal',
    'pp': 'Papua New Guinea',
    'pr': 'Puerto Rico',
    'pt': 'Portuguese Timor',  # Discontinued
    'pw': 'Palau',
    'py': 'Paraguay',
    'qa': 'Qatar',
    'qea': 'Australia',  # Queensland
    'quc': 'Canada',  # Québec (Province)
    'rb': 'Serbia',
    're': 'Réunion',
    'rh': 'Zimbabwe',
    'riu': 'United States of America',  # Rhode Island
    'rm': 'Romania',
    'ru': 'Russia',
    'rur': 'Russian S.F.S.R.',  # Discontinued
    'rw': 'Rwanda',
    'ry': 'Ryukyu Islands, Southern',  # Discontinued
    'sa': 'South Africa',
    'sb': 'Svalbard',  # Discontinued
    'sc': 'Saint-Barthélemy',
    'scu': 'United States of America',  # South Carolina
    'sd': 'South Sudan',
    'sdu': 'United States of America',  # South Dakota
    'se': 'Seychelles',
    'sf': 'Sao Tome and Principe',
    'sg': 'Senegal',
    'sh': 'Spanish North Africa',
    'si': 'Singapore',
    'sj': 'Sudan',
    'sk': 'Sikkim',  # Discontinued
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Sint Maarten',
    'snc': 'Canada',  # Saskatchewan
    'so': 'Somalia',
    'sp': 'Spain',
    'sq': 'Swaziland',
    'sr': 'Surinam',
    'ss': 'Western Sahara',
    'st': 'Saint-Martin',
    'stk': 'Scotland',
    'su': 'Saudi Arabia',
    'sv': 'Swan Islands',  # Discontinued
    'sw': 'Sweden',
    'sx': 'Namibia',
    'sy': 'Syria',
    'sz': 'Switzerland',
    'ta': 'Tajikistan',
    'tar': 'Tajik S.S.R.',  # Discontinued
    'tc': 'Turks and Caicos Islands',
    'tg': 'Togo',
    'th': 'Thailand',
    'ti': 'Tunisia',
    'tk': 'Turkmenistan',
    'tkr': 'Turkmen S.S.R.',  # Discontinued
    'tl': 'Tokelau',
    'tma': 'Australia',  # Tasmania
    'tnu': 'United States of America',  # Tennessee
    'to': 'Tonga',
    'tr': 'Trinidad and Tobago',
    'ts': 'United Arab Emirates',
    'tt': 'Trust Territory of the Pacific Islands',  # Discontinued
    'tu': 'Turkey',
    'tv': 'Tuvalu',
    'txu': 'United States of America',  # Texas
    'tz': 'Tanzania',
    'ua': 'Egypt',
    'uc': 'United States Miscellaneous Caribbean Islands',
    'ug': 'Uganda',
    'ui': 'United Kingdom Miscellaneous Islands',  # Discontinued
    'uik': 'United Kingdom Miscellaneous Islands',
    'uk': 'United Kingdom',  # Discontinued
    'un': 'Ukraine',
    'unr': 'Ukraine',  # Discontinued
    'up': 'United States Miscellaneous Pacific Islands',
    'ur': 'Soviet Union',  # Discontinued
    'us': 'United States of America',  # Discontinued
    'utu': 'United States of America',  # Utah
    'uv': 'Burkina Faso',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'uzr': 'Uzbek S.S.R.',  # Discontinued
    'vau': 'United States of America',  # Virginia
    'vb': 'British Virgin Islands',
    'vc': 'Vatican City',
    've': 'Venezuela',
    'vi': 'Virgin Islands of the United States',
    'vm': 'Vietnam',
    'vn': 'Vietnam, North',  # Discontinued
    # 'vp': 'Various places',
    'vra': 'Australia',  # Victoria
    'vs': 'Vietnam, South',  # Discontinued
    'vtu': 'United States of America',  # Vermont
    'wau': 'United States of America',  # Washington (State)
    'wb': 'West Berlin',  # Discontinued
    'wea': 'Australia',  # Western Australia
    'wf': 'Wallis and Futuna',
    'wiu': 'United States of America',  # Wisconsin
    'wj': 'West Bank of the Jordan River',
    'wk': 'Wake Island',
    'wlk': 'Wales',
    'ws': 'Samoa',
    'wvu': 'United States of America',  # West Virginia
    'wyu': 'United States of America',  # Wyoming
    'xa': 'Christmas Island (Indian Ocean)',
    'xb': 'Cocos (Keeling) Islands',
    'xc': 'Maldives',
    'xd': 'Saint Kitts-Nevis',
    'xe': 'Marshall Islands',
    'xf': 'Midway Islands',
    'xga': 'Australia',  # Coral Sea Islands Territory
    'xh': 'Niue',
    'xi': 'Saint Kitts-Nevis-Anguilla',  # Discontinued
    'xj': 'Saint Helena',
    'xk': 'Saint Lucia',
    'xl': 'Saint Pierre and Miquelon',
    'xm': 'Saint Vincent and the Grenadines',
    'xn': 'Macedonia',
    'xna': 'Australia',  # New South Wales
    'xo': 'Slovakia',
    'xoa': 'Australia',  # Northern Territory
    'xp': 'Spratly Island',
    'xr': 'Czech Republic',
    'xra': 'Australia',  # South Australia
    'xs': 'South Georgia and the South Sandwich Islands',
    'xv': 'Slovenia',
    'xxc': 'Canada',
    'xxk': 'United Kingdom',
    'xxr': 'Soviet Union',  # Discontinued
    'xxu': 'United States of America',
    'ye': 'Yemen',
    'ykc': 'Canada',  # Yukon Territory
    'ys': 'Yemen (People\'s Democratic Republic)',  # Discontinued
    'yu': 'Serbia and Montenegro',  # Discontinued
    'za': 'Zambia',
}

# Lookup table for languages
languages = {
    'aar': 'Afar',
    'abk': 'Abkhazian',
    'ace': 'Achinese',
    'ach': 'Acoli',
    'ada': 'Adangme',
    'ady': 'Adyghe',
    'afa': 'Afro-Asiatic languages',
    'afh': 'Afrihili',
    'afr': 'Afrikaans',
    'ain': 'Ainu',
    'ajm': 'Aljamia',  # Discontinued
    'aka': 'Akan',
    'akk': 'Akkadian',
    'alb': 'Albanian',
    'ale': 'Aleut',
    'alg': 'Algonquian languages',
    'alt': 'Altai',
    'amh': 'Amharic',
    'ang': 'English, Old (ca. 450-1100)',
    'anp': 'Angika',
    'apa': 'Apache languages',
    'ara': 'Arabic',
    'arc': 'Official Aramaic (700-300 BCE)',
    'arg': 'Aragonese',
    'arm': 'Armenian',
    'arn': 'Mapuche',
    'arp': 'Arapaho',
    'art': 'Artificial languages',
    'arw': 'Arawak',
    'asm': 'Assamese',
    'ast': 'Asturian',
    'ath': 'Athapascan languages',
    'aus': 'Australian languages',
    'ava': 'Avaric',
    'ave': 'Avestan',
    'awa': 'Awadhi',
    'aym': 'Aymara',
    'aze': 'Azerbaijani',
    'bad': 'Banda languages',
    'bai': 'Bamileke languages',
    'bak': 'Bashkir',
    'bal': 'Baluchi',
    'bam': 'Bambara',
    'ban': 'Balinese',
    'baq': 'Basque',
    'bas': 'Basa',
    'bat': 'Baltic languages',
    'bej': 'Beja',
    'bel': 'Belarusian',
    'bem': 'Bemba',
    'ben': 'Bengali',
    'ber': 'Berber languages',
    'bho': 'Bhojpuri',
    'bih': 'Bihari languages',
    'bik': 'Bikol',
    'bin': 'Bini',
    'bis': 'Bislama',
    'bla': 'Siksika',
    'bnt': 'Bantu languages',
    'bos': 'Bosnian',
    'bra': 'Braj',
    'bre': 'Breton',
    'btk': 'Batak languages',
    'bua': 'Buriat',
    'bug': 'Buginese',
    'bul': 'Bulgarian',
    'bur': 'Burmese',
    'byn': 'Blin',
    'cad': 'Caddo',
    'cai': 'Central American Indian languages',
    'cam': 'Khmer',  # Discontinued
    'car': 'Galibi Carib',
    'cat': 'Catalan',
    'cau': 'Caucasian languages',
    'ceb': 'Cebuano',
    'cel': 'Celtic languages',
    'cha': 'Chamorro',
    'chb': 'Chibcha',
    'che': 'Chechen',
    'chg': 'Chagatai',
    'chi': 'Chinese',
    'chk': 'Chuukese',
    'chm': 'Mari',
    'chn': 'Chinook jargon',
    'cho': 'Choctaw',
    'chp': 'Chipewyan',
    'chr': 'Cherokee',
    'chu': 'Church Slavic',
    'chv': 'Chuvash',
    'chy': 'Cheyenne',
    'cmc': 'Chamic languages',
    'cop': 'Coptic',
    'cor': 'Cornish',
    'cos': 'Corsican',
    'cpe': 'Creoles and pidgins, English based',
    'cpf': 'Creoles and pidgins, French-based',
    'cpp': 'Creoles and pidgins, Portuguese-based',
    'cre': 'Cree',
    'crh': 'Crimean Tatar',
    'crp': 'Creoles and Pidgins',
    'csb': 'Kashubian',
    'cus': 'Cushitic languages',
    'cze': 'Czech',
    'dak': 'Dakota',
    'dan': 'Danish',
    'dar': 'Dargwa',
    'day': 'Land Dayak languages',
    'del': 'Delaware',
    'den': 'Slave (Athapascan)',
    'dgr': 'Dogrib',
    'din': 'Dinka',
    'div': 'Divehi',
    'doi': 'Dogri',
    'dra': 'Dravidian languages',
    'dsb': 'Lower Sorbian',
    'dua': 'Duala',
    'dum': 'Dutch, Middle (ca. 1050-1350)',
    'dut': 'Dutch',
    'dyu': 'Dyula',
    'dzo': 'Dzongkha',
    'efi': 'Efik',
    'egy': 'Egyptian (Ancient)',
    'eka': 'Ekajuk',
    'elx': 'Elamite',
    'eng': 'English',
    'enm': 'English, Middle (1100-1500)',
    'epo': 'Esperanto',
    'esk': 'Eskimo',  # Discontinued
    'esp': 'Esperanto',  # Discontinued
    'est': 'Estonian',
    'eth': 'Ethiopic',  # Discontinued
    'ewe': 'Ewe',
    'ewo': 'Ewondo',
    'fan': 'Fang',
    'fao': 'Faroese',  # Discontinued
    'far': 'Faroese',
    'fat': 'Fanti',
    'fij': 'Fijian',
    'fil': 'Filipino',
    'fin': 'Finnish',
    'fiu': 'Finno-Ugrian languages',
    'fon': 'Fon',
    'fre': 'French',
    'fri': 'Frisian',  # Discontinued
    'frm': 'French, Middle (ca. 1300-1600)',
    'fro': 'French, Old (ca. 842-1300)',
    'frr': 'Northern Frisian',
    'frs': 'Eastern Frisian',
    'fry': 'Western Frisian',
    'ful': 'Fulah',
    'fur': 'Friulian',
    'gaa': 'Ga',
    'gae': 'Scottish Gaelix',  # Discontinued
    'gag': 'Galician',  # Discontinued
    'gal': 'Oromo',  # Discontinued
    'gay': 'Gayo',
    'gba': 'Gbaya',
    'gem': 'Germanic languages',
    'geo': 'Georgian',
    'ger': 'German',
    'gez': 'Geez',
    'gil': 'Gilbertese',
    'gla': 'Gaelic',
    'gle': 'Irish',
    'glg': 'Galician',
    'glv': 'Manx',
    'gmh': 'German, Middle High (ca.1050-1500)',
    'goh': 'German, Old High (ca.750-1050)',
    'gon': 'Gondi',
    'gor': 'Gorontalo',
    'got': 'Gothic',
    'grb': 'Grebo',
    'grc': 'Greek, Ancient (to 1453)',
    'gre': 'Greek, Modern (1453-)',
    'grn': 'Guarani',
    'gsw': 'Swiss German',
    'gua': 'Guarani',  # Discontinued
    'guj': 'Gujarati',
    'gwi': 'Gwichin',
    'hai': 'Haida',
    'hat': 'Haitian',
    'hau': 'Hausa',
    'haw': 'Hawaiian',
    'heb': 'Hebrew',
    'her': 'Herero',
    'hil': 'Hiligaynon',
    'him': 'Western Pahari languages',
    'hin': 'Hindi',
    'hit': 'Hittite',
    'hmn': 'Hmong',
    'hmo': 'Hiri Motu',
    'hrv': 'Croatian',
    'hsb': 'Upper Sorbian',
    'hun': 'Hungarian',
    'hup': 'Hupa',
    'iba': 'Iban',
    'ibo': 'Igbo',
    'ice': 'Icelandic',
    'ido': 'Ido',
    'iii': 'Sichuan Yi',
    'ijo': 'Ijo languages',
    'iku': 'Inuktitut',
    'ile': 'Interlingue',
    'ilo': 'Iloko',
    'ina': 'Interlingua (International Auxiliary Language Association)',
    'inc': 'Indic languages',
    'ind': 'Indonesian',
    'ine': 'Indo-European languages',
    'inh': 'Ingush',
    'int': 'Interlingua (International Auxiliary Language Association)',  # Discontinued
    'ipk': 'Inupiaq',
    'ira': 'Iranian languages',
    'iri': 'Irish',  # Discontinued
    'iro': 'Iroquoian languages',
    'ita': 'Italian',
    'jav': 'Javanese',
    'jbo': 'Lojban',
    'jpn': 'Japanese',
    'jpr': 'Judeo-Persian',
    'jrb': 'Judeo-Arabic',
    'kaa': 'Kara-Kalpak',
    'kab': 'Kabyle',
    'kac': 'Kachin',
    'kal': 'Kalatdlisut',
    'kam': 'Kamba',
    'kan': 'Kannada',
    'kar': 'Karen languages',
    'kas': 'Kashmiri',
    'kau': 'Kanuri',
    'kaw': 'Kawi',
    'kaz': 'Kazakh',
    'kbd': 'Kabardian',
    'kha': 'Khasi',
    'khi': 'Khoisan languages',
    'khm': 'Central Khmer',
    'kho': 'Khotanese',
    'kik': 'Kikuyu',
    'kin': 'Kinyarwanda',
    'kir': 'Kirghiz',
    'kmb': 'Kimbundu',
    'kok': 'Konkani',
    'kom': 'Komi',
    'kon': 'Kongo',
    'kor': 'Korean',
    'kos': 'Kosraean',
    'kpe': 'Kpelle',
    'krc': 'Karachay-Balkar',
    'krl': 'Karelian',
    'kro': 'Kru languages',
    'kru': 'Kurukh',
    'kua': 'Kuanyama',
    'kum': 'Kumyk',
    'kur': 'Kurdish',
    'kus': 'Kusaie',  # Discontinued
    'kut': 'Kutenai',
    'lad': 'Ladino',
    'lah': 'Lahnda',
    'lam': 'Lamba',
    'lan': 'Occitan (post 1500)',  # Discontinued
    'lao': 'Lao',
    'lap': 'Sami',  # Discontinued
    'lat': 'Latin',
    'lav': 'Latvian',
    'lez': 'Lezghian',
    'lim': 'Limburgan',
    'lin': 'Lingala',
    'lit': 'Lithuanian',
    'lol': 'Mongo',
    'loz': 'Lozi',
    'ltz': 'Luxembourgish',
    'lua': 'Luba-Lulua',
    'lub': 'Luba-Katanga',
    'lug': 'Ganda',
    'lui': 'Luiseno',
    'lun': 'Lunda',
    'luo': 'Luo (Kenya and Tanzania)',
    'lus': 'Lushai',
    'mac': 'Macedonian',
    'mad': 'Madurese',
    'mag': 'Magahi',
    'mah': 'Marshallese',
    'mai': 'Maithili',
    'mak': 'Makasar',
    'mal': 'Malayalam',
    'man': 'Mandingo',
    'mao': 'Maori',
    'map': 'Austronesian languages',
    'mar': 'Marathi',
    'mas': 'Masai',
    'may': 'Malay',
    'max': 'Manx',  # Discontinued
    'mdf': 'Moksha',
    'mdr': 'Mandar',
    'men': 'Mende',
    'mga': 'Irish, Middle (900-1200)',
    'mic': 'Mikmaq',
    'min': 'Minangkabau',
    'mkh': 'Mon-Khmer languages',
    'mla': 'Malagasy',  # Discontinued
    'mlg': 'Malagasy',
    'mlt': 'Maltese',
    'mnc': 'Manchu',
    'mni': 'Manipuri',
    'mno': 'Manobo languages',
    'moh': 'Mohawk',
    'mol': 'Moldavian',  # Discontinued
    'mon': 'Mongolian',
    'mos': 'Mossi',
    'mun': 'Munda languages',
    'mus': 'Creek',
    'mwl': 'Mirandese',
    'mwr': 'Marwari',
    'myn': 'Mayan languages',
    'myv': 'Erzya',
    'nah': 'Nahuatl languages',
    'nai': 'North American Indian languages',
    'nap': 'Neapolitan',
    'nau': 'Nauru',
    'nav': 'Navajo',
    'nbl': 'South Ndebele',
    'nde': 'North Ndebele',
    'ndo': 'Ndonga',
    'nds': 'Low German',
    'nep': 'Nepali',
    'new': 'Nepal Bhasa',
    'nia': 'Nias',
    'nic': 'Niger-Kordofanian languages',
    'niu': 'Niuean',
    'nno': 'Norwegian Nynorsk',
    'nob': 'Norwegian Bokml',
    'nog': 'Nogai',
    'non': 'Norse, Old',
    'nor': 'Norwegian',
    'nqo': 'NKo',
    'nso': 'Pedi',
    'nub': 'Nubian languages',
    'nwc': 'Classical Newari',
    'nya': 'Chichewa',
    'nym': 'Nyamwezi',
    'nyn': 'Nyankole',
    'nyo': 'Nyoro',
    'nzi': 'Nzima',
    'oci': 'Occitan (post 1500)',
    'oji': 'Ojibwa',
    'ori': 'Oriya',
    'orm': 'Oromo',
    'osa': 'Osage',
    'oss': 'Ossetian',
    'ota': 'Turkish, Ottoman (1500-1928)',
    'oto': 'Otomian languages',
    'paa': 'Papuan languages',
    'pag': 'Pangasinan',
    'pal': 'Pahlavi',
    'pam': 'Pampanga',
    'pan': 'Punjabi',
    'pap': 'Papiamento',
    'pau': 'Palauan',
    'peo': 'Persian, Old (ca.600-400 )',
    'per': 'Persian',
    'phi': 'Philippine languages',
    'phn': 'Phoenician',
    'pli': 'Pali',
    'pol': 'Polish',
    'pon': 'Pohnpeian',
    'por': 'Portuguese',
    'pra': 'Prakrit languages',
    'pro': 'Provenal, Old (to 1500)',
    'pus': 'Pushto',
    'que': 'Quechua',
    'raj': 'Rajasthani',
    'rap': 'Rapanui',
    'rar': 'Rarotongan',
    'roa': 'Romance languages',
    'roh': 'Romansh',
    'rom': 'Romany',
    'rum': 'Romanian',
    'run': 'Rundi',
    'rup': 'Aromanian',
    'rus': 'Russian',
    'sad': 'Sandawe',
    'sag': 'Sango',
    'sah': 'Yakut',
    'sai': 'South American Indian languages',
    'sal': 'Salishan languages',
    'sam': 'Samaritan Aramaic',
    'san': 'Sanskrit',
    'sao': 'Samoan',  # Discontinued
    'sas': 'Sasak',
    'sat': 'Santali',
    'scn': 'Sicilian',
    'scc': 'Serbian',  # Discontinued
    'sco': 'Scots',
    'scr': 'Croatian',  # Discontinued
    'sel': 'Selkup',
    'sem': 'Semitic languages',
    'sga': 'Irish, Old (to 900)',
    'sgn': 'Sign Languages',
    'shn': 'Shan',
    'sho': 'Shona',  # Discontinued
    'sid': 'Sidamo',
    'sin': 'Sinhala',
    'sio': 'Siouan languages',
    'sit': 'Sino-Tibetan languages',
    'sla': 'Slavic languages',
    'slo': 'Slovak',
    'slv': 'Slovenian',
    'sma': 'Southern Sami',
    'sme': 'Northern Sami',
    'smi': 'Sami languages',
    'smj': 'Lule Sami',
    'smn': 'Inari Sami',
    'smo': 'Samoan',
    'sms': 'Skolt Sami',
    'sna': 'Shona',
    'snd': 'Sindhi',
    'snh': 'Sinhalese',  # Discontinued
    'snk': 'Soninke',
    'sog': 'Sogdian',
    'som': 'Somali',
    'son': 'Songhai languages',
    'sot': 'Sotho, Southern',
    'spa': 'Spanish',
    'srd': 'Sardinian',
    'srn': 'Sranan Tongo',
    'srp': 'Serbian',
    'srr': 'Serer',
    'ssa': 'Nilo-Saharan languages',
    'sso': 'Sotho',  # Discontinued
    'ssw': 'Swati',
    'suk': 'Sukuma',
    'sun': 'Sundanese',
    'sus': 'Susu',
    'sux': 'Sumerian',
    'swa': 'Swahili',
    'swe': 'Swedish',
    'swz': 'Swazi',  # Discontinued
    'syc': 'Classical Syriac',
    'syr': 'Syriac',
    'tag': 'Tagalog',  # Discontinued
    'tah': 'Tahitian',
    'tai': 'Tai languages',
    'taj': 'Tajik',  # Discontinued
    'tam': 'Tamil',
    'tar': 'Tatar',  # Discontinued
    'tat': 'Tatar',
    'tel': 'Telugu',
    'tem': 'Timne',
    'ter': 'Tereno',
    'tet': 'Tetum',
    'tgk': 'Tajik',
    'tgl': 'Tagalog',
    'tha': 'Thai',
    'tib': 'Tibetan',
    'tig': 'Tigre',
    'tir': 'Tigrinya',
    'tiv': 'Tiv',
    'tkl': 'Tokelau',
    'tlh': 'Klingon',
    'tli': 'Tlingit',
    'tmh': 'Tamashek',
    'tog': 'Tonga (Nyasa)',
    'ton': 'Tongan',
    'tpi': 'Tok Pisin',
    'tru': 'Truk',  # Discontinued
    'tsi': 'Tsimshian',
    'tsn': 'Tswana',
    'tso': 'Tsonga',
    'tsw': 'Tswana',  # Discontinued
    'tuk': 'Turkmen',
    'tum': 'Tumbuka',
    'tup': 'Tupi languages',
    'tur': 'Turkish',
    'tut': 'Altaic languages',
    'tvl': 'Tuvalu',
    'twi': 'Twi',
    'tyv': 'Tuvinian',
    'udm': 'Udmurt',
    'uga': 'Ugaritic',
    'uig': 'Uighur',
    'ukr': 'Ukrainian',
    'umb': 'Umbundu',
    'urd': 'Urdu',
    'uzb': 'Uzbek',
    'vai': 'Vai',
    'ven': 'Venda',
    'vie': 'Vietnamese',
    'vol': 'Volapk',
    'vot': 'Votic',
    'wak': 'Wakashan languages',
    'wal': 'Wolaitta',
    'war': 'Waray',
    'was': 'Washo',
    'wel': 'Welsh',
    'wen': 'Sorbian languages',
    'wln': 'Walloon',
    'wol': 'Wolof',
    'xal': 'Kalmyk',
    'xho': 'Xhosa',
    'yao': 'Yao',
    'yap': 'Yapese',
    'yid': 'Yiddish',
    'yor': 'Yoruba',
    'ypk': 'Yupik languages',
    'zap': 'Zapotec',
    'zbl': 'Bliss',
    'zen': 'Zenaga',
    'zgh': 'Standard Moroccan Tamazight',
    'zha': 'Zhuang',
    'znd': 'Zande languages',
    'zul': 'Zulu',
    'zun': 'Zuni',
    'zza': 'Zaza',
}

# Lookup table for publication frequencies
frequencies = {
    # '#':	'No determinable frequency',
    'a': 'Annual',
    'b': 'Bi-monthly',
    'c': 'Semi-weekly',
    'd': 'Daily',
    'e': 'Bi-weekly',
    'f': 'Semi-annual',
    'g': 'Biennial',
    'h': 'Triennial',
    'i': 'Tri-weekly',  # 3 times a week
    'j': 'Tri-monthly',  # 3 times a month
    'k': 'Continuously updated',
    'm': 'Monthly',
    'q': 'Quarterly',
    's': 'Semi-monthly',
    't': 'Tri-annual',  # 3 times a year
    # 'u':	'Unknown',
    'w': 'Weekly',
    # 'z':	'Other',
    # '|':	'No attempt to code',
}

# Lookup table for musical composition forms
musical_forms = {
    'an': 'anthems',
    'bd': 'ballads',
    'bg': 'bluegrass music',
    'bl': 'blues',
    'bt': 'ballets',
    'ca': 'chaconnes',
    'cb': 'chants (religions other than Christianity)',
    'cc': 'Christian chants',
    'cg': 'concerti grossi',
    'ch': 'chorales',
    'cl': 'chorale preludes',
    'cn': 'canons and rounds',
    'co': 'concertos',
    'cp': 'polyphonic chansons',
    'cr': 'carols',
    'cs': 'chance compositions',
    'ct': 'cantatas',
    'cy': 'country music',
    'cz': 'canzonas',
    'df': 'dance forms',
    'dv': 'divertimentos, serenades, cassations, divertissements, and notturni',
    'fg': 'fugues',
    'fl': 'flamenco',
    'fm': 'folk music',
    'ft': 'fantasias',
    'gm': 'gospel music',
    'hy': 'hymns',
    'jz': 'jazz',
    'mc': 'musical revues and comedies',
    'md': 'madrigals',
    'mi': 'minuets',
    'mo': 'motets',
    'mp': 'motion picture music',
    'mr': 'marches',
    'ms': 'masses',
    'mz': 'mazurkas',
    'nc': 'nocturnes',
    'op': 'operas',
    'or': 'oratorios',
    'ov': 'overtures',
    'pg': 'program music',
    'pm': 'passion music',
    'po': 'polonaises',
    'pp': 'popular music',
    'pr': 'preludes',
    'ps': 'passacaglias',
    'pt': 'part-songs',
    'pv': 'pavans',
    'rc': 'rock music',
    'rd': 'rondos',
    'rg': 'ragtime music',
    'ri': 'ricercars',
    'rp': 'rhapsodies',
    'rq': 'requiems',
    'sd': 'square dance music',
    'sg': 'songs',
    'sn': 'sonatas',
    'sp': 'symphonic poems',
    'st': 'studies and exercises',
    'su': 'suites',
    'sy': 'symphonies',
    'tc': 'toccatas',
    'tl': 'teatro lirico',
    'ts': 'trio-sonatas',
    'vi': 'villancicos',
    'vr': 'variations',
    'wz': 'waltzes',
    'za': 'zarzuelas',
}
