#!/usr/bin/env python
# -*- coding: utf8 -*-

"""Classes for cleaning publisher names in the Researcher Format transformation."""

import regex as re
import sys

__author__ = 'Victoria Morris'
__license__ = 'MIT License'
__version__ = '1.0.0'
__status__ = '4 - Beta Development'


class PublisherMultiRegex(object):
    regexes = ()

    def __init__(self):
        try: self._rx = re.compile('|'.join(self.regexes), flags=re.IGNORECASE)
        except:
            for r in self.regexes:
                try: re.compile(r)
                except: print('Error in regex: {}'.format(str(r)))

    def sub(self, s):
        if not s or s is None: return ''
        return self._rx.sub(self._sub, s)

    def _sub(self, mo):
        try:
            for k, v in mo.groupdict().items():
                if v:
                    if k == 'AllElse':
                        return ''
                    if 'UUU' in str(k):
                        return bytes(str(k).replace('UUU', '\\' + 'u'), 'ascii').decode('unicode-escape')
                    try:                         
                        sub = getattr(self, k)
                        if callable(sub): return sub(mo)
                        else: return sub
                    except: return str(k)
                    
        except:
            print('\nError PMR: {0}\n'.format(str(sys.exc_info())))


class Publishers(PublisherMultiRegex):
    # Need to put \b before initials
    regexes = (
        r'(?P<AaronUUU0020Arrowsmith>^a(aron)?[.\s]*arrowsmith.*)',
        r'(?P<Abacus>^(wells\s*)?abacus\b.*)',
        r'(?P<AbacusUUU0020Communications>^abacus\s*communicat.*)',
        r'(?P<AbacusUUU0020House>^abacus\s*house.*)',
        r'(?P<AbacusUUU002DKent>^abacus[\s\-]*kent.*)',
        r'(?P<AberdeenUUU0020Independent>^aberdeen\s*independent.*)',
        r'(?P<Abrams>^abrams\s*book.*)',
        r'(?P<ABS>^a[.\s]*b[.\s]*s\b[.\s]*pub.*)',
        r'(?P<ActesUUU0020Sud>^actes[\s\-]*sud[\s\-]*(pap)?.*)',
        r'(?P<AdamsUUU0020Media>^adams\s*media.*)',
        r'(?P<AdvertiserUUU0020Group>^advertiser\s*group.*)',
        r'(?P<AfricaUUU0020World>^africa\s*world\s*press.*)',
        r'(?P<AHM>^a[.\s]*h[.\s]*m\b[.\s]*pub.*)',
        r'(?P<AhmadiyyaUUU0020AnjumanUUU0020IshaUUU0027atUUU0020Islam>^ahmadiyya.*?\banjuman.*?\bislam.*)',
        r'(?P<Ajanta>^ajanta\s*pub.*)',
        r'(?P<AkademieUUU0020derWissenschaftenUUU0020UUU0026UUU0020derUUU0020Literatur>^akad.*?\bwissenschaft.*?\bliteratur.*)',
        r'(?P<AkademischeUUU0020DruckUUU002DUUU0020UUU0026UUU0020Verlagsanstalt>^akad.*?\bdr.ck.*?\bverl.*)',
        r'(?P<AlbanyUUU0020CountyUUU0020SecondaryUUU0020BoysUUU0027UUU0020School>^albany.*?\bco.*?\bsec.*?\bboy.*)',
        r'(?P<AldershotUUU0020News>^aldershot\s*news.*)',
        r'(?P<Alioth>^alioth\s*press.*)',
        r'(?P<Aliquando>^aliquando\s*press.*)',
        r'(?P<AllenUUU0020Lane>^allen\s*lane\b.*)',
        r'(?P<AllisonUUU0020UUU0026UUU0020Busby>^all[iy]son.*?\bbusby.*)',
        r'(?P<Allworth>^allworth\s*press.*)',
        r'(?P<AlmqvistUUU0020UUU0026UUU0020Wiksell>^almqvist.*?\bwiksell.*)',
        r'(?P<AlphaUUU0020Newspapers>^alpha\s*news.*)',
        r'(?P<AlUUU002DArab>^al[\s\-]+arab\b.*)',
        r'(?P<AlUUU002DGarida>^al-*garida\s*press.*)',
        r'(?P<AlUUU002DMaaref>^al-*maaref\s*press.*)',
        r'(?P<AmberUUU0020Lane>^amber\s*lane\s*press.*)',
        r'(?P<Amberley>^amberley(.*?\b(press|pub).*)?)',
        r'(?P<AmericanUUU0020Heritage>^american\s*heritage\s*pub.*)',
        r'(?P<Amies>^amies\s*pub.*)',
        r'(?P<Ammonite>^ammonite(.*?\b(press|pub).*)?)',
        r'(?P<AMS>^ams\s*press.*)',
        r'(?P<Anthem>^anthem\s*press.*)',
        r'(?P<AnthonyUUU0020GibbsUUU0020UUU0026UUU0020Phillips>^(a(nthony)? )?\bgibbs.*?\bphil*i*ps.*)',
        r'(?P<Antioch>^antioch\s*press.*)',
        r'(?P<Anvil>^anvil\s*press.*)',
        r'(?P<Apollon>^apollon\s*press.*)',
        r'(?P<Applause>^applause.*?\btheatre.*)',
        r'(?P<Apple>^apple(.*?\b(press|pub).*)?)',
        r'(?P<AppletonUUU002DCenturyUUU002DCrofts>^appleton.*?\bcent.*?\bcr[ao]ft.*)',
        r'(?P<AquinasUUU0020SocietyUUU003BBlackfriars>^aquinas.*?\bsoc.*?\bblackfriar.*)',
        r'(?P<Arcadian>^arcadian\s*press.*)',
        r'(?P<Archant>^archant\b.*)',
        r'(?P<Archaeopress>^archaeopress(.*?\b(archaeo|press|pub).*)?)',
        r'(?P<ArchibaldUUU0020Constable>^ar(ch)?(ibal|ibol|iblan)?d?.*?\bconstable.*)',
        r'(?P<ArchibaldUUU0020ConstableUUU003BBrashUUU0020UUU0026UUU0020Reid>^ar(ch)?(ibal|ibol|iblan)?d?[,.\-\s]*constable.*?\bbrash.*?\breid.*)',
        r'(?P<ArchibaldUUU0020ConstableUUU003BConstableUUU002CUUU0020HunterUUU002CUUU0020ParkUUU0020UUU0026UUU0020Hunter>^ar(ch)?(ibal|ibol|iblan)?d?[,.\-\s]*constable.*?\bconstable.*?\bhunter.*?\bpark.*?\bhunter.*)',
        r'(?P<ArchibaldUUU0020ConstableUUU003BFairburnUUU0020UUU0026UUU0020Anderson>^ar(ch)?(ibal|ibol|iblan)?d?[,.\-\s]*constable.*?\bfairbairn.*?\banderson.*)',
        r'(?P<ArchibaldUUU0020ConstableUUU003BRobertUUU0020Ross>^ar(ch)?(ibal|ibol|iblan)?d?[,.\-\s]*constable.*?\brobert\s*ross.*)',
        r'(?P<Arcturus>^arcturus\s*pub.*)',
        r'(?P<ArdenUUU0020ShakespeareUUU003BThomson>^arden.*?\bshakespeare.*?\bthomson.*)',
        r'(?P<ArdenUUU003BBloomsbury>^bloomsbury.*?\barden.*)',
        r'(?P<Argonaut>^argonaut\s*press.*)',
        r'(?P<Ariel>^ariel\s*press.*)',
        r'(?P<Arion>^arion\s*press.*)',
        r'(?P<ArisUUU0020UUU0026UUU0020Phillips>^ar[iy]s.*?\bphil*i*ps.*)',
        r'(?P<ArisUUU0020UUU0026UUU0020PhillipsUUU003BGibbUUU0020MemorialUUU0020Trust>^ar[iy]s.*?\bphil*i*ps.*?\bgibb\s*memorial.*)',
        r'(?P<Ark>^ark\s*press.*)',
        r'(?P<Arnold>^arnold\s*book.*)',
        r'(?P<ArnoldUUU0020Heinemann>^arnold.*?\bheinemann.*)',
        r'(?P<ArnoldUUU0020Hodder>^arnold\s*hodder.*)',
        r'(?P<ArnoldUUU003BOxfordUUU0020UniversityUUU0020Press>^arnold.*?\boxford.*?\buni.*)',
        r'(?P<ArnoldUUU003BSchoolsUUU0020Council>^arnold.*?\bschool.*?\bcouncil.*)',
        r'(?P<ArnoldUUU003BUniversityUUU0020Press>^arnold.*?\buniversity.*)',
        r'(?P<ArthurUUU0020JUUU0020CassellUUU003BFavershamUUU0020Society>^(arthur\s*j[.\s]*cassel*.*?\bfaversham\s*soc|faversham\s*soc.*?\barthur\s*j[.\s]*cassel*).*)',
        r'(?P<ArtsUUU0020CouncilUUU0020ofUUU0020NorthernUUU0020Ireland>^art.*?\bcouncil.*?\bnorth.*?\birel.*)',
        r'(?P<Ashgate>^ashgate\s*pub.*)',
        r'(?P<AssociatedUUU0020BusinessUUU0020ProgrammesUUU003BCassell>^associated\s*business\s*program.*?\bcassel*.*)',
        r'(?P<AssociatedUUU0020Newspapers>^associated\s*news.*)',
        r'(?P<AssociatedUUU0020UniversityUUU0020Presses>^associated\s*university\s*press\s*es.*)',
        r'(?P<Astolat>^astolat\s*press.*)',
        r'(?P<AtelierUUU0020NationalUUU0020deUUU0020RUUU00E9productionUUU0020desUUU0020ThUUU00E8ses>^atelier.*?\bnational.*?\br.prod.*?\bth.se.*)',
        r'(?P<AthenaeumUUU0020ofUUU0020Philadelphia>^athena?eum.*?\bphiladelphia.*.*)',
        r'(?P<AthenUUU00E6um>^athen.*?um\s*press.*)',
        r'(?P<Athlone>^athlone\s*press.*)',
        r'(?P<AtlanticUUU0020Monthly>^atlantic\s*monthly\s*press.*)',
        r'(?P<AtomicUUU0020WeaponsUUU0020ResearchUUU0020Establishment>^atomic.*?\bweapon.*?\bresearch.*?\best.*)',
        r'(?P<AubierUUU002DFlammarion>^aubier.*?\bflammarit?on.*)',
        r'(?P<AubierUUU002DMontaigne>^aubier.*?\bmontaigne.*)',
        r'(?P<Aufbau>^aufbau[\s\-]*(verlag)?$)',
        r'(?P<AustralianUUU0020NationalUUU0020University>^australian?\s*national\s*uni.*)',
        r'(?P<AuthorHouse>^authorhouse.*)',
        r'(?P<AutomobileUUU0020AssociationUUU003BCassell>^automobile\s*association.*?\bcassel*.*)',
        r'(?P<AUUU0020AUUU0020MUUU0020Stols>^a[.\s]*a[.\s]*m[.\s]*stols\b.*)',
        r'(?P<AUUU0020Constable>^[0-9xi\-\.\s]*a[,.\-\s]*constable.*)',
        r'(?P<AUUU0020DUUU0020CaratzasUUU003BOrpheus>^a[.\s]*d[.\s]*caratzas.*?\borpheus.*)',
        r'(?P<Avantgarde>^avantgarde\s*press.*)',
        r'(?P<BackUUU0020Bay>^back\s*bay\b.*)',
        r'(?P<BaconUUU0020Society>^bacon\s*society.*)',
        r'(?P<Badger>^badger\s*pub.*)',
        r'(?P<BailliUUU00E8reUUU0020UUU0026UUU0020Cassell>^bi?ai?l*i.\s*b?re?.*?\bcassel*.*)',
        r'(?P<BailliUUU00E8reUUU002CUUU0020TindallUUU0020UUU0026UUU0020Cassell>^bi?ai?l*i.\s*b?re?.*?\btindal*.*?\bcassel*.*)',
        r'(?P<BakerUUU003BRichards>^baker.*?\brichards.*)',
        r'(?P<Ballantyne>^ballantyne\s*press.*)',
        r'(?P<Ballard>^ballard\s*pub.*)',
        r'(?P<Bancroft>^bancroft\b.*)',
        r'(?P<BanksUUU0020Music>^banks\s*music.*)',
        r'(?P<Barbarian>^barbarian\s*press.*)',
        r'(?P<BargainUUU0020Pages>^bargain\s*pages.*)',
        r'(?P<BarronUUU0027s>^barron.?s\s*educ.*)',
        r'(?P<Barry>^barry\s*print.*)',
        r'(?P<BasicUUU0020English>^basic\s*english\s*pub.*)',
        r'(?P<BathUUU0020Newspapers>^bath\s*news.*)',
        r'(?P<Batsford>^batsford\s*(educ|acad).*)',
        r'(?P<Baudry>^baudry.?seuro.*)',
        r'(?P<BaumgUUU00E4rtner>^baumg.rtner.*)',
        r'(?P<BBC>^british\s*broadcasting.*)',
        r'(?P<Beacon>^beacon\s*press.*)',
        r'(?P<BedsUUU0020Times>^beds\s*times\s*pub.*)',
        r'(?P<BelfastUUU0020Telegraph>^belfast\s*telegraph.*)',
        r'(?P<Belknap>^belknap\s*press.*)',
        r'(?P<BelknapUUU003BHarvardUUU0020UniversityUUU0020Press>^belknap.*?\bharvard.*)',
        r'(?P<BellesUUU0020Lettres>^(soci.t. d.*dition)?\s*(les)?belles[\s\-]*lettres$)',
        r'(?P<BellUUU0020UUU0026UUU0020Daldy>^bell.*?\bda[ld]+y.*)',
        r'(?P<BelwinUUU002DMills>^belwin.*?\bmills.*)',
        r'(?P<BenjaminUUU0020Donne>^benj(ami)?\s*n\s*donne.*)',
        r'(?P<BerksUUU0020UUU0026UUU0020BucksUUU0020Observer>^berks.*?\bbucks.*?\bobserver.*)',
        r'(?P<BernhardUUU0020Tauchnitz>^bernhard.*?\btauchnitz.*)',
        r'(?P<BerrowUUU0027sUUU0020Newspapers>^berrow.*?\bnews.*)',
        r'(?P<BFI>^BFI\b.*)',
        r'(?P<BibliographicalUUU0020SocietyUUU0020ofUUU0020theUUU0020UniversityUUU0020ofUUU0020Virginia>^bibliog.*?\bsoc.*?\buniv.*?\bvirginia.*)',
        r'(?P<BibliothUUU00E8queUUU0020Nationale>^biblioth.que\s*nationale.*)',
        r'(?P<BillingtonUUU0020UUU0026UUU0020Wright>^billington (&|and) wright.*)',
        r'(?P<BirminghamUUU0020PublicUUU0020Libraries>^birmingham\s*public.*)',
        r'(?P<BirnUUU0020Brothers>^birn bro.*)',
        r'(?P<BlackUUU0020Dog>^black.*?\bdog(.*?\b(press|pub).*)?)',
        r'(?P<BlackUUU0020Swan>^black\s*swan\s*press.*)',
        r'(?P<Blackwell>^blackwell\s*pub.*)',
        r'(?P<Blaisdell>^blaisdell\s*pub.*)',
        r'(?P<Blandford>^blandford\s*press.*)',
        r'(?P<BlissUUU002CUUU0020Sands>^bliss[\,\s\-]*sands$)',
        r'(?P<Blizzard>^blizzard\s*pub.*)',
        r'(?P<Bloom>^bloom\'*s\s*(lit).*)',
        r'(?P<Bloomsbury>^bloomsbury.*)',
        r'(?P<BondUUU0020StreetUUU0020Publications>^bond st(reet)? pub.*)',
        r'(?P<BookUUU0020Guild>^book.*?\bguild(.*?\b(press|pub).*)?)',
        r'(?P<BookUUU0020Now>^book\s*now\s*pub.*)',
        r'(?P<BooksUUU0020ofUUU0020Africa>^books.*?\bof.*?\bafrica.*)',
        r'(?P<BooseyUUU0020UUU0026UUU0020Hawkes>^boosey.*?\bh.wkes.*)',
        r'(?P<BorderUUU0020Weeklies>^border\s*weeklies.*)',
        r'(?P<Borealis>^borealis\s*press.*)',
        r'(?P<Bounty>^bounty\b.*)',
        r'(?P<Bountyhunter>^bounty.*?hunter.*)',
        r'(?P<BountyUUU0020Hunter>^bounty.*?\s+hunter.*)',
        r'(?P<BPMUUU0020Media>^b[.\s]*p[.\s]*m[.\s]*media.*)',
        r'(?P<BradburyUUU0020UUU0026UUU0020Evans>^bradbury.*?\bevans.*)',
        r'(?P<BradburyUUU002CUUU0020Agnew>^bradbury.*?\bagnew.*)',
        r'(?P<Brealey>^brealey\b.*)',
        r'(?P<BreitkopfUUU0020UUU0026UUU0020HUUU00E4rtel>^breitkopf.*?\bh.*?rtel.*)',
        r'(?P<Brendin>^brendin\s*pub.*)',
        r'(?P<Brepols>^brepols\b.*)',
        r'(?P<BritaUUU0020LiteraturaUUU0020kajUUU0020DebataUUU0020Societo>^brita.*?\bliteratura.*?\bdebata.*?\bsocieto.*)',
        r'(?P<BritishUUU0020CouncilUUU003BNationalUUU0020BookUUU0020League>.*\bbritish.*?council.*?national.*?book.*?league.*)',
        r'(?P<BritishUUU0020CouncilUUU003BNationalUUU0020BookUUU0020LeagueUUU003BLongmansUUU002CUUU0020Green>.*\bbritish.*?council.*?national.*?book.*?league.*?longman.*)',
        r'(?P<BritishUUU0020Library>.*\bbritish library.*)',
        r'(?P<BritishUUU0020Museum>^british\s*museum\s*press.*)',
        r'(?P<BritishUUU0020SchoolUUU0020ofUUU0020ArcheologyUUU0020inUUU0020Iraq>^british.*?\barcheo.*?\biraq.*)',
        r'(?P<BritishUUU0020ShakespeareUUU0020Association>.*\bbritish shakespeare.*)',
        r'(?P<Broadview>^broadview\s*press.*)',
        r'(?P<Broadway>^broadway\s*pub.*)',
        r'(?P<BrookUUU0020UUU0026UUU0020Chrystal>^brook.*?\bch?rystal.*)',
        r'(?P<BuckinghamshireUUU0020UUU0026UUU0020HertfordshireUUU0020Newspapers>^buck.*?\bhert.*?\bnews.*)',
        r'(?P<Bulfinch>^bull?finch\b.*)',
        r'(?P<BUUU0020R>^b\s*r\s*pub.*)',
        r'(?P<BUUU0020UUU0026UUU0020D>^b\s*(&|and|et|und)\s*d\s*pub.*)',
        r'(?P<BUUU00E4renreiter>^b.renreiter.*)',
        r'(?P<Buvington>^buvington\s*press.*)',
        r'(?P<CalthaUUU0020Kit>^caltha\s*kit\s*pub.*)',
        r'(?P<Cambria>^cambria\s*press.*)',
        r'(?P<CambridgeUUU0020Learning>^cambridge learning.*)',
        r'(?P<CambridgeUUU0020Scholars>^cambridge\s*scholars\s*pub.*)',
        r'(?P<CambridgeUUU0020UniversityUUU0020Press>^c(ambridge|AMBRIDGE)\s*univ(er)?(sity)?\s*(pr)?(ess)?$)',
        r'(?P<CandlelightUUU0020Productions>^candlelight\s*product.*)',     # Not modified from here
        r'(?P<Candlestick>^candlestick\s*press.*)',
        r'(?P<Candlewick>^candlewick\s*press.*)',
        r'(?P<CanUUU0020ofUUU0020Worms>^can\s*of\s*worms\s*press.*)',
        r'(?P<Capital>^capital\s*news.*)',
        r'(?P<Capra>^capra\s*press.*)',
        r'(?P<Carcanet>^carcanet\s*press.*)',
        r'(?P<Carel>^carel\s*press.*)',
        r'(?P<CareyUUU0020Kingsgate>^carey\s*kingsgate\s*press.*)',
        r'(?P<CarlUUU0020Winter>^carl\s*winter.*)',
        r'(?P<CarnegieUUU0020UnitedUUU0020KingdomUUU0020TrusteesUUU003BTUUU0020UUU0026UUU0020AUUU0020Constable>.*\bcarnegie\s*u(nited)?[.\s]*k(ingdom)?\.*.*?trustee.*?\bt.*?\ba.*?\bconstable.*)',
        r'(?P<Carysfort>^carysfort\s*press.*)',
        r'(?P<Casanova>^casanova\s*press.*)',
        r'(?P<Casemate>^casemate.*)',
        r'(?P<Cassandra>^cassandra\s*press.*)',
        r'(?P<Cassell>^([0-9]+\s*)?(cassel*\s*i[.\s]*e[.\s]*)?(press\s*of\s*)?cassell*.*)',
        r'(?P<CassellUUU0020Farm>^cas+el+.*?farm.*)',
        r'(?P<CassellUUU0020Military>^cas+el+.*?military.*)',
        r'(?P<CassellUUU002CUUU0020PetterUUU002CUUU0020Galpin>^cas+el+.*?p[oe][ltr]*ti?er.*?[gc]a[lp]+h?in.*)',
        r'(?P<CassellUUU003BCollierUUU0020Macmillan>^cas+el+.*?collier.*?macmillan.*)',
        r'(?P<CassellUUU003BDonnington>^cas+el+.*?donnington.*)',
        r'(?P<CastleUUU002DPierce>^castle-*pierce\s*press.*)',
        r'(?P<Catbird>^catbird\s*press.*)',
        r'(?P<Caxton>^caxton\s*pub.*)',
        r'(?P<Cayme>^cayme\s*press.*)',
        r'(?P<Celtic>^celtic\s*(educ).*)',
        r'(?P<Cengage>^cengage\s*(learn).*)',
        r'(?P<Centaur>^centaur\s*press.*)',
        r'(?P<CentreUUU0020forUUU0020MedievalUUU0020StudiesUUU003BPontificalUUU0020InstituteUUU0020ofUUU0020MediaevalUUU0020Studies>^(pontific.*?inst.*?mediaeval.*?stud.*?cent.*?medieval.*?stud|cent.*?medieval.*?stud.*?pontific.*?inst.*?mediaeval.*?stud).*)',
        r'(?P<CentreUUU0020forUUU0020WorldUUU0020DevelopmentUUU0020Education>^centre for world development education.*)',
        r'(?P<Chambers>^chambers\s*(young\s*set\s*dictionaries).*)',
        r'(?P<ChamerotUUU0020UUU0026UUU0020Renouard>.*\bchamerot.*?renouard.*)',
        r'(?P<Chancellor>^chancellor\s*press.*)',
        r'(?P<ChannelUUU0020FourUUU0020Television>^channel\s*four(\s*television(\s*corporation)?)?$)',
        r'(?P<CharingUUU0020Cross>^charing\s*cross\s*pub.*)',
        r'(?P<CharlesUUU0020Scribner>^charles.*?scribner.*)',
        r'(?P<CharteredUUU0020InstituteUUU0020ofUUU0020Building>^charter.*?institute.*?build.*)',
        r'(?P<CharteredUUU0020InstituteUUU0020ofUUU0020BuildingUUU003BAtom>^charter.*?institute.*?build.*?atom.*)',
        r'(?P<CharteredUUU0020InstitutionUUU0020ofUUU0020BuildingUUU0020Services>^charter.*?institution.*?build.*?service.*)',
        r'(?P<Chaucer>^chaucer\s*press.*)',
        r'(?P<CheltenhamUUU0020Newspapers>^cheltenham news.*)',
        r'(?P<Cherrytree>^cherrytree\s*press.*)',
        r'(?P<ChesterUUU0020ChronicleUUU003BAssociatedUUU0020Newspapers>^chester chronicle (and|&) associated newspapers?.*)',
        r'(?P<ChicagoUUU0020Review>^chicago\s*review\s*press.*)',
        r'(?P<Chiron>^chiron\s*pub.*)',
        r'(?P<Chiswick>^chiswick\s*press.*)',
        r'(?P<ChristianUUU0020Science>^christian science.*)',
        r'(?P<ChrisUUU0020Kington>^chris\s*kington\s*pub.*)',
        r'(?P<Circle>^circle\s*press.*)',
        r'(?P<Citadel>^citadel\s*press.*)',
        r'(?P<CJB>^c[.\s]*j[.\s]*b\.*\s+.*)',
        r'(?P<Clairmont>^clairmont\s*press.*)',
        r'(?P<Clarendon>^clarendon\s*press.*)',
        r'(?P<Clematis>^clematis\s*pub.*)',
        r'(?P<ClipperUUU0020Audio>^clipper(.*?\b(audio|large|press|pub).*)?)',
        r'(?P<Clover>^clover\s*press.*)',
        r'(?P<Clunie>^clunie\s*press.*)',
        r'(?P<CobdenUUU0020ClubUUU003BCassell>^cobden.*?club.*?cassel*.*)',
        r'(?P<Coburn>^coburn\s*pub.*)',
        r'(?P<Coleman>^coleman\s*pub.*)',
        r'(?P<Coles>^coles\s*pub.*)',
        r'(?P<Colleagues>^colleagues\s*press.*)',
        r'(?P<CollectorUUU0027sUUU0020Library>^collector.?s\s*library.*)',
        r'(?P<CollierUUU002DMacmillan>^collier.*?mac[\s\-]*millan.*)',
        r'(?P<Collins>^collins(.*?\b(clear|educ|press|pub).*)?)',
        r'(?P<ColoradoUUU0020College>.*\bcolorado\s*college.*)',
        r'(?P<Commercial>^commercial\s*press.*)',
        r'(?P<Comstock>^comstock.*)',
        r'(?P<ConcordeUUU003BWardUUU0020Lock>^concorde.*?ward\s*lock.*)',
        r'(?P<ConranUUU0020Octopus>^(cont?ran\s*octopus|octopus\s*cont?ran).*)',
        r'(?P<ConranUUU0020Octopus>^conran.*?oct[aeiou]*p[aeiou]*s.*)',
        r'(?P<Constable>^(dublin,*\s*)?constable\s*((young|U S A).*|s*$))',
        r'(?P<ConstableUUU002CUUU0020HunterUUU002CUUU0020ParkUUU0020UUU0026UUU0020Hunter>^constable,?\s*hunter,?\s*park,?\s(&|and)?,?\s*hunter.*)',
        r'(?P<ConstableUUU002CUUU0020HurstUUU002CUUU0020Robinson>^(constable.*?hurst.*?robinson|hurst.*?robinson.*?constable).*)',
        r'(?P<ConstableUUU003BArlington>^constable.*?arlington.*)',
        r'(?P<ConstableUUU003BEdinburghUUU0020UniversityUUU0020Press>^constable.*?edinburgh.*?uni.*)',
        r'(?P<ConstableUUU003BOldUUU0020GlenalmondUUU0020Club>^constable.*?glen\s*almond.*)',
        r'(?P<ConstableUUU003BScottishUUU0020HistoryUUU0020Society>^constable.*?scottish.*?history.*)',
        r'(?P<ConstableUUU003BUniversityUUU0020Press>^constable.*?university.*)',
        r'(?P<ConsumersUUU0027UUU0020Association>^consumer[\'s]* association.*)',
        r'(?P<CooperativaUUU0020LibrariaUUU0020IULM>^co[\s\-]*operativa\s*libraria\s*I[\.\s]*U[\.\s]*L[\.\s]*M.*)',
        r'(?P<Cornhill>^cornhill\s*pub.*)',
        r'(?P<Cornmarket>^cornmarket\s*press.*)',
        r'(?P<Cosmopolis>^cosmopolis\s*press.*)',
        r'(?P<CotmanUUU0020HouseUUU003BJarrold>^cotman.*?house.*?jarrold.*)',
        r'(?P<Cottingham>^cottingham\s*press.*)',
        r'(?P<Counterpath>^counterpath\s*press.*)',
        r'(?P<Courier>^courier print.*)',
        r'(?P<Cranach>^cranach\s*press.*)',
        r'(?P<CRC>^crc\s*press.*)',
        r'(?P<CrUUU00E8meUUU0020deUUU0020laUUU0020Crime>^cr.me.*?\bde.*?\bla.*?\bcrime.*)',
        r'(?P<CrUUU00E9cy>^cr.cy(.*?\b(press|pub).*)?)',        
        r'(?P<CrowellUUU002DCollier>^crowell-*collier\s*press.*)',
        r'(?P<CRW>^crw\s*pub.*)',
        r'(?P<Cube>^cube\s*press.*)',
        r'(?P<CumberlandUUU0020UUU0026UUU0020WestmorlandUUU0020Herald>^cumberland (and|&) westmorland herald.*)',
        r'(?P<Currency>^currency\s*press.*)',
        r'(?P<Curtain>^curtain\s*press.*)',
        r'(?P<Curwen>^curwen\s*press.*)',
        r'(?P<CUUU0020Bathurst>^c[\.\s]*bathurst.*)',
        r'(?P<CUUU0020BathurstUUU003BWUUU0020Strahan>^c[\.\s]*bathurst.*?strahan.*)',
        r'(?P<CUUU0020C>^c\s*c\s*pub.*)',
        r'(?P<CUUU0020Etherington>^c[\.\s]*etherington.*)',
        r'(?P<CUUU0020FUUU0020Peters>^c[.\s]*f[.\s]*peters.*)',
        r'(?P<DailyUUU0020Mail>^daily\s*mail\s*press.*)',
        r'(?P<Dana>^dana\s*press.*)',
        r'(?P<DasUUU0020MusikinstrumentUUU0020inUUU0020Komm>^(verlag\s*)?(das)?musikinstrument.*?komm.*)',
        r'(?P<Daurus>^daurus\s*press.*)',
        r'(?P<DaUUU0020Capo>^da\s*capo\s*press.*)',
        r'(?P<DaUUU0020CapoUUU003BBUUU0020Blom>^da\s*capo.*?blom.*)',
        r'(?P<DavidUUU0020J>^david.*?\bj(.*?\b(press|pub).*)?)',
        r'(?P<DayUUU0020One>^day.*?\bone(.*?\b(press|pub).*)?)',
        r'(?P<DCSF>^dcsf\s*pub.*)',
        r'(?P<DCUUU0020Thomson>^d[.\s]*c[.\s]*thomson.*)',
        r'(?P<Dedalus>^dedalus\s*press.*)',
        r'(?P<Delacorte>^delacorte\s*press.*)',
        r'(?P<Delalain>^delalain.*)',
        r'(?P<Dell>^dell\s*pub.*)',
        r'(?P<Dent>^dent\s*(child).*)',
        r'(?P<DerbyshireUUU0020Times>^derbyshire times.*)',
        r'(?P<DerryUUU0020Journal>^derry journal.*)',
        r'(?P<Deveron>^deveron\s*press.*)',
        r'(?P<Dial>^dial\s*press.*)',
        r'(?P<Didier>^didier.*)',
        r'(?P<Diploma>^diploma\s*press.*)',
        r'(?P<Do>^do\s*press.*)',
        r'(?P<Dolmen>^dolmen\s*press.*)',
        r'(?P<Dolphin>^dolphin.*)',
        r'(?P<DonningtonUUU0020PressUUU003BCassell>^donnington.*?p.*?cassel*.*)',
        r'(?P<Dover>^a*dover(?![a-z]).*)',
        r'(?P<DoverUUU003BConstable>^a*dover.*?constable.*)',
        r'(?P<Doves>^doves\s*press.*)',
        r'(?P<Dramaline>^dramaline\s*pub.*)',
        r'(?P<Dunmore>^dunmore\s*press.*)',
        r'(?P<EasternUUU0020CountiesUUU0020Newspapers>^eastern counties news.*)',
        r'(?P<EastUUU0020AnglianUUU0020DailyUUU0020Times>^east anglian? daily times.*)',
        r'(?P<EastUUU0020SurreyUUU0020UUU0026UUU0020SussexUUU0020Newspapers>^east surrey (&|and) sussex news.*)',
        r'(?P<Ebenezer>^ebenezer\s*press.*)',
        r'(?P<Ebury>^ebury\s*press.*)',
        r'(?P<Echo>^echo\s+.*)',
        r'(?P<Edinburgh>^edinburgh\s*pub.*)',
        r'(?P<EditioUUU0020Musica>^editio\s+musica$)',
        r'(?P<EdwardUUU0020Arnold>^edward[\s\.\'\-,]*arnold.*)',
        r'(?P<EdwardUUU0020Churton>^edward.*?churton.*)',
        r'(?P<EdwardUUU0020Elgar>^edward.*?\belgar(.*?\b(press|pub).*)?)',
        r'(?P<EdwinUUU0020Mellen>^edwin\s*mellen\s*press.*)',
        r'(?P<Egerton>^egerton\s*press.*)',
        r'(?P<Egmont>^egmont\s+.*)',
        r'(?P<Elizabethan>^elizabethan\s*press.*)',
        r'(?P<ElizabethanUUU0020Club>.*\belizabethan\s*club.*)',
        r'(?P<ELM>^elm\s*pub.*)',
        r'(?P<EMAP>^e[.\s]*m[.\s]*a[.\s]*p\.*\s+.*)',
        r'(?P<EMAPUUU0020Anglia>^e[.\s]*m[.\s]*a[.\s]*p[.\s]*anglia.*)',
        r'(?P<EmeraldUUU0020Knight>^emerald\s*knight\s*pub.*)',
        r'(?P<EncyclopaediaUUU0020Britannica>^encyclo.*?britan*ic*a.*)',
        r'(?P<EngineeringUUU0020EquipmentUUU0020UsersUUU0027UUU0020Association>^engineering equipment users.? assoc.*)',
        r'(?P<EpochUUU0020Times>^epoch times.*)',
        r'(?P<Epworth>^epworth\s*press.*)',
        r'(?P<Equinox>^equinox(.*?\b(press|pub).*)?)',
        r'(?P<Esperanto>^esperanto\s*pub.*)',
        r'(?P<EssexUUU0020Chronicle>^essex chronicle.*)',
        r'(?P<Ettrick>^ettrick\s*press.*)',
        r'(?P<EugenicsUUU0020SocietyUUU003BCassell>^eugenic.*?soc.*?cassel*.*)',
        r'(?P<Euphorion>^euphorion.*)',
        r'(?P<Eureka>^eureka\s*press.*)',
        r'(?P<EustonUUU0020Grove>^euston\s*grove\s*press.*)',
        r'(?P<EUUU0020DomUUU00E8nech>.*\be\s*dom.nech.*)',
        r'(?P<EUUU0020Jeffery>^[0-9\.\,\-\s]*E\s*Jeffery$)',
        r'(?P<EUUU0020JUUU0020Arnold>^e[.\s]*j[.\s]*arnold.*)',
        r'(?P<EUUU0020JUUU0020ArnoldUUU003BNuffieldUUU0020Foundation>^e[.\s]*j[.\s]*arnold.*?nuffield.*)',
        r'(?P<EUUU0020JUUU0020ArnoldUUU003BSchoolsUUU0020Council>^e[.\s]*j[.\s]*arnold.*?school.*?council.*)',
        r'(?P<EUUU0020Mellen>^e\s*mellen\s*press.*)',
        r'(?P<Evans>^evans\s+(bro)?.*)',
        r'(?P<Everyman>^everyman.*)',
        r'(?P<EverymanUUU0027sUUU0020Library>^everyman.*?library.*)',
        r'(?P<EverymanUUU0027sUUU0020LibraryUUU003BDent>^everyman.*?library.*?dent.*)',
        r'(?P<Ewer>^ewer\s+.*)',
        r'(?P<Exemplar>^exemplar\s*pub.*)',
        r'(?P<Experiment>^experiment\s*press.*)',
        r'(?P<Exposition>^exposition\s*press.*)',
        r'(?P<Express>^express\s*pub.*)',
        r'(?P<Eyewitness>.*\beye[\s\-]*witness.*)',
        r'(?P<FaberUUU0020UUU0026UUU0020Faber>^faber.*?faber.*)',
        r'(?P<FabianUUU0020Society>^fabian(?![a-z]).*)',
        r'(?P<Face>^face\s*press.*)',
        r'(?P<FactsUUU0020onUUU0020File>^facts.*?on.*?file.*)',
        r'(?P<FacultyUUU0020ofUUU0020ActuariesUUU003BTUUU0020UUU0026UUU0020AUUU0020Constable>.*\bfaculty.*?actuar.*?\bt.*?\ba.*?constable.*)',
        r'(?P<FairleighUUU0020DickinsonUUU0020UniveristyUUU0020PressUUU003BRowmanUUU0020UUU0026UUU0020Littlefield>^fairleigh.*?dickinson.*?uni.*?rowman.*?littlefield.*)',
        r'(?P<Falcon>^falcon\s*press.*)',
        r'(?P<FarrarUUU002CUUU0020StrausUUU0020UUU0026UUU0020Giroux>.*\bfarrar.*?straus.*?giroux.*)',
        r'(?P<Fastprint>^fastprint\s*pub.*)',
        r'(?P<Fawcett>^fawcett\s*pub.*)',
        r'(?P<Fazer>^(edn\s*)?fazer$)',
        r'(?P<FGI>^fgi\s*pub.*)',
        r'(?P<FinancialUUU0020Times>.*\bfinancial times.*)',
        r'(?P<FirminUUU0020Didot>.*\bfirmin.*?didot.*)',
        r'(?P<FisherUUU0020Miller>.*\bfisher.*?miller.*)',
        r'(?P<Folcroft>.*\bfolcroft.*)',
        r'(?P<Fonthill>^fonthill(.*?\b(media|press|pub).*)?)',
        r'(?P<Foolscap>^foolscap\s*press.*)',
        r'(?P<Forum>^forum\s*pub.*)',
        r'(?P<Fountain>^fountain\s*pub.*)',
        r'(?P<FourthUUU0020Dimension>^fourth\s*dimension\s*pub.*)',
        r'(?P<FourUUU0020Courts>^four\s*courts\s*press.*)',
        r'(?P<FrancesUUU0020Lincoln>.*\bfrances.*?lincoln.*)',
        r'(?P<FrancisUUU0020Carr>^francis\s*carr\s*pub.*)',
        r'(?P<FrederickUUU0020Ungar>^frederick\s*ungar\s*pub.*)',
        r'(?P<FreeUUU0020Age>^free\s*age\s*press.*)',
        r'(?P<Friary>^friary\s*press.*)',
        r'(?P<Futura>.*\bfutura\s+.*)',
        r'(?P<FUUU0020Busse>^(comission\s*bei\s*)?f[.\s]*busse$)',
        r'(?P<Gaia>^(young\s*)?gaia.*)',
        r'(?P<GainsboroughUUU0020House>^gainsborough.*?\bhouse(.*?\b(press|pub).*)?)',
        r'(?P<GardenUUU0020Art>^garden.*?\bart(.*?\b(press|pub).*)?)',
        r'(?P<GardenUUU0020City>^garden\s*city\s*press.*)',
        r'(?P<Garland>^garland\s*pub.*)',
        r'(?P<Garnier>^garnier\s+.*)',
        r'(?P<Gateway>^(b )?gateway\s*(book.*|p)$)',
        r'(?P<Gawthorn>^gawthorn\s*press.*)',
        r'(?P<Gehenna>^gehenna\s*press.*)',
        r'(?P<Genius>.*\bgenius\s*K.nyvkiad.*)',
        r'(?P<GeorgeUUU0020Cawthorn>^george.*?\bcawthorn.*)',
        r'(?P<GeorgeUUU0020WashingtonUUU0020UniversityUUU003BSouthernUUU0020IllinoisUUU0020UniversityUUU0020Press>^george.*?\bwashington.*?\buni.*?\bsout.*?\billinois.*?\buni.*)',
        r'(?P<GeorgUUU0020Olms>^georg.*?\bolms.*)',
        r'(?P<Giles>^giles\s*pub.*)',
        r'(?P<GillUUU0020UUU0026UUU0020Macmillan>^gill.*?\bmacmillan.*)',
        r'(?P<GinnUUU0020UUU0026UUU0020Heath>^ginn.*?heath.*)',
        r'(?P<Glasgow>^glasgow\s*pub.*)',
        r'(?P<GlasgowUUU0020UniversityUUU0020LibraryUUU003BArtUUU0020GalleryUUU0020ofUUU0020OntarioUUU003BMiller>^glasgow.*?univers.*?librar.*?gallery.*?ontario.*?miller.*)',
        r'(?P<Gleaner>^gleaner\s+.*)',
        r'(?P<Glenbridge>^glenbridge\s*pub.*)',
        r'(?P<GlintingBlue>^glintingblue\s*press.*)',
        r'(?P<GlobeUUU0020Playhouse>^globe\s*playhouse\s*pub.*)',
        r'(?P<Godsfield>^godsfield\s*(book).*)',
        r'(?P<GoldenUUU0020Cockerel>^golden\s*cockerel\s*press.*)',
        r'(?P<GoldenUUU0020Eagle>^golden\s*eagle\s*press.*)',
        r'(?P<GoldenUUU0020Vista>^golden\s*vista\s*press.*)',
        r'(?P<Gollancz>^(b )?gollancz.*)',
        r'(?P<Goodmusic>^goodmusic\s*pub.*)',
        r'(?P<Gordian>^gordian\s*press.*)',
        r'(?P<GovernmentUUU0020ofUUU0020IndiaUUU003BJohnUUU0020Murray>^government.*?india.*?john\s*murray.*)',
        r'(?P<Grabhorn>^grabhorn\s*press.*)',
        r'(?P<Graham>^graham\s*pub.*)',
        r'(?P<Grail>^grail\s*pub.*)',
        r'(?P<GrandUUU0020Central>^grand\s+central.*)',
        r'(?P<Greenhaven>^greenhaven\s*press.*)',
        r'(?P<GreenUUU0020Bank>^green\s*bank\s*press.*)',
        r'(?P<Greenways>^greenways\s+.*)',
        r'(?P<Greenwood>^greenwood\s*press.*)',
        r'(?P<Gresham>^gresham\s*pub.*)',
        r'(?P<Greville>^greville\s*press.*)',
        r'(?P<Greystones>^greystones\s*press.*)',
        r'(?P<Griffin>^griffin\s*press.*)',
        r'(?P<GriffithUUU0020UUU0026UUU0020Farran>^griffith.*?farran.*)',
        r'(?P<GrosvenorUUU0020House>^grosven[eo]r.*?\bhouse(.*?\b(press|pub).*)?)',
        r'(?P<Grove>^grove\s*press.*)',
        r'(?P<GuardianUUU0020Newspapers>^guardian news.*)',
        r'(?P<GuardianUUU002CUUU0020GazetteUUU002CUUU0020IndependentUUU0020UUU0026UUU0020Citizen>^guardian,? gazette,? independent (&|and) citizen.*)',
        r'(?P<Gupta>^gupta\s*press.*)',
        r'(?P<GuthrieUUU0020Newspapers>^guthrie news.*)',
        r'(?P<GUUU0020UUU0026UUU0020ANUUU0020Scott>^g\.?\s*(&|and)\s*A\.?\s*N\.?\s*Scott.*)',
        r'(?P<GyldendalskeUUU0020Boghandel>^gyldendalske.*?boghandel.*)',
        r'(?P<Hachette>^\'*(biblioth.que|classiques|le?|(obtained from the )?(libraire|US by))?\s*hachette.*)',
        r'(?P<Hackett>^hackett\s*pub.*)',
        r'(?P<Hafner>^hafner\s*pub.*)',
        r'(?P<Halcyon>^halcyon\s*press.*)',
        r'(?P<HamishUUU0020Hamilton>^h(amish)?\s*hamilton.*)',
        r'(?P<Hamlin>^hamlin\s*pub.*)',
        r'(?P<Hamlyn>^hamlyn\s*(c1987|child|paper|pub).*)',
        r'(?P<HamlynUUU003BBison>^hamlyn.*?bison.*)',
        r'(?P<HampsteadUUU0020UUU0026UUU0020HighgateUUU0020Express>^hampstead (&|and) highgate express.*)',
        r'(?P<HandUUU0020UUU0026UUU0020Flower>^hand\s*(&|and|et|und)\s*flower\s*press.*)',
        r'(?P<HansardUUU0020SocietyUUU003BCassell>^hansard.*?soc.*?cassel*.*)',
        r'(?P<Harper>^harper\s*(press|sanfran).*)',
        r'(?P<HarperCollins>^harper.*?collins.*)',
        r'(?P<Harvester>^harvester\s*press.*)',
        r'(?P<Haus>^haus\s*pub.*)',
        r'(?P<Haymarket>^haymarket\s+.*)',
        r'(?P<Headline>^headline bo?o?kp?u?b?.*)',
        r'(?P<HeadlineUUU0020Review>^headline review.*)',
        r'(?P<HeartUUU0027sUUU0020Core>^heart\'*s\s*core\s*pub.*)',
        r'(?P<Heinemann>^heinemann\s+(educ|young).*)',
        r'(?P<HeinemannUUU003BBBCUUU003BBritishUUU0020Coucil>^heinemann.*?\bbritish\s*Broadcasting.*?\bbritish.*?\bcouncil.*)',
        r'(?P<Hemisphere>^hemisphere(?![a-z]).*)',
        r'(?P<HendonUUU0020Times>^hendon times.*)',
        r'(?P<HenryUUU0020Playford>^henry\s*playford.*)',
        r'(?P<Herald>^herald\s*press.*)',
        r'(?P<HeraldUUU0020Express>^herald\s*express.*)',
        r'(?P<Herbert>^herbert\s*press.*)',
        r'(?P<Heritage>^heritage\s*press.*)',
        r'(?P<HertsUUU0020UUU0026UUU0020EssexUUU0020Newspapers>^herts.*?\bessex.*?\bnews.*)',
        r'(?P<HillUUU0020Brothers>^hill bro.*)',
        r'(?P<HKM>^h[.\s]*k[.\s]*m\.*\s+.*)',
        r'(?P<Hodder>^hodd[e ]r\s*((bro(ther)?s)|p(aper)?b(ac)?ks?).*)',
        r'(?P<HodderUUU0020Arnold>^hodd[e ]r\s*ar*n*old.*)',
        r'(?P<HodderUUU0020ChildrenUUU0027s>^hodd[e ]r\s*child.*)',
        r'(?P<HodderUUU0020Christian>^hodd[e ]r\s*christian.*)',
        r'(?P<HodderUUU0020Dargaud>^hodd[e ]r\s*darga[un]d.*)',
        r'(?P<HodderUUU0020Fawcett>^hodd[e ]r\s*(and|&|\-)?\s*fawcett?.*)',
        r'(?P<HodderUUU0020Gibson>^hodd[e ]r\s*gib?son.*)',
        r'(?P<HodderUUU0020Headline>^hodd[e ]r\s*headline.*)',
        r'(?P<HodderUUU0020Mobius>^hodd[e ]r\s*mobius.*)',
        r'(?P<HodderUUU0020UUU0026UUU0020Stoughton>^[0-9ecpliv\-\.\s]*hodd[e ]*[rtn]*\s*(&|an?[des]|7|\-)?\s*s[tl]*r?o?[u ]*[gh]*[ty ]*n?o?[nm]?.*)',
        r'(?P<Hokuseido>^hokuseido\s*press.*)',
        r'(?P<Holywell>^holywell\s*press.*)',
        r'(?P<HoughtonUUU0020Mifflin>^houghton.*?mif*l*in$)',
        r'(?P<Howard>^howard\s*pub.*)',
        r'(?P<HumanitiesUUU002DEbooks>^humanities.*?e[\.\-\s]*book.*)',
        r'(?P<HurstUUU002CUUU0020Robinson>^(edinburgh,*\s*)?7*\s*hurst[&,\s]*robinson$)',
        r'(?P<Hutchinson>^Hutchinson.*)',
        r'(?P<HutchinsonUUU0020UniversityUUU0020Library>^hutchinson.*?\buni.*?\blib.*)',
        r'(?P<HUUU0020FUUU0020WitherbyUUU003BWildfowlUUU0020Trust>^h[.\s]*f[.\s]*witherby.*?\bwildfowl.*)',
        r'(?P<HUUU0020HerringmanUUU003BRUUU0020Bentley>^H[\.\s]*Herringman.*?\br[\.\s]*Bentley.*)',
        r'(?P<HUUU0020KUUU0020Lewis>^h[.\s]*k[.\s]*lewis.*)',
        r'(?P<HUUU002CUUU0020Woodfall>^H[\.\,\s]*Woodfall.*)',
        r'(?P<IDG>^IDG.*)',
        r'(?P<IDW>^idw\s*pub.*)',
        r'(?P<Ignatius>^ignatius\s*press.*)',
        r'(?P<IIndependentUUU0020Print>^independent print(\s+.*|$))',
        r'(?P<Ikuta>^ikuta\s*press.*)',
        r'(?P<Imagine>^imagine\s*pub.*)',
        r'(?P<Impact>^impact print.*)',
        r'(?P<ImperialUUU0020FederationUUU0020LeagueUUU003BCassell>^imperial.*?federation.*?league.*?cassel*.*)',
        r'(?P<ImperialUUU0020WarUUU0020Museum>^imperial.*?\bwar.*?\bmuseum.*)',
        r'(?P<IndependentUUU0020Fox>^independent fox.*)',
        r'(?P<IndependentUUU0020Newspapers>^independent news.*)',
        r'(?P<IndependentUUU0020PublishersUUU0020Group>.*\bindependent.*?\bpublisher.*?\bgroup.*)',
        r'(?P<InkyUUU0020Parrot>^inky\s*parrot.*)',
        r'(?P<Insel>^(im\s*)?insel\s*verl.*)',
        r'(?P<InstituteUUU0020ofUUU0020PsychoanalysisUUU003BBailliUUU00e8reUUU002CUUU0020TindallUUU0020UUU0026UUU0020Cassell>^institute.*?psycho\-*analysis.*?bi?ai?l*i.\s*b?re?.*?tindal*.*?cassel*.*)',
        r'(?P<InstitutUUU0020fUUU00FCrUUU0020AnglistikUUU0020UUU0026UUU0020AmerikanistikUUU002CUUU0020UniversitUUU00E4tUUU0020Salzburg>^inst.*?anglist.*?amerikan.*?salzburg.*)',
        r'(?P<InstitutUUU0020fUUU00FCrUUU0020EnglischeUUU0020SpracheUUU0020UUU0026UUU0020LiteraturUUU002CUUU0020UniversitUUU00E4tUUU0020Salzburg>^inst.*?engl.*?sprach.*?literat.*?salzburg.*)',
        r'(?P<InterUUU002DParliamentaryUUU0020UnionUUU003BCassell>^[io]nter.*?parliamentary.*?union.*?cassel*.*)',
        r'(?P<InUUU0020TheUUU0020Saddle>^in the saddle.*)',
        r'(?P<IsaacUUU0020IaggardUUU003BEdUUU0020Blount>^Isaac.*?\biaggard.*?\bed.*?\bblount.*)',
        r'(?P<ISBS>^(USA (&|and) Canada by )?ISBS.*)',
        r'(?P<IslandUUU0020Publishing>^island pub.*)',
        r'(?P<IUniverse>^Iuniverse.*)',
        r'(?P<Ivy>^ivy\s*press.*)',
        r'(?P<Jacaranda>^jacaranda\s*press.*)',
        r'(?P<Jackdaw>^jackdaw\s*pub.*)',
        r'(?P<JamesUUU0020DaniellUUU0020UUU0026UUU0020CompanyUUU002CUUU0020NoUUU00206UUU0020GreatUUU0020CharlotteUUU0020StreetUUU002CUUU0020BlackfriarsUUU0020Road>.*\bjames daniell.*?charlotte.*?blackfriar.*)',
        r'(?P<JamesUUU0020Maclehose>^j(ames)?.*?maclehose(?! &).*)',
        r'(?P<JamesUUU0020MaclehoseUUU003BUniversityUUU0020Press>^j(ames)?.*?maclehose.*?uni.*)',
        r'(?P<Janopakarini>^janopakarini\s*press.*)',
        r'(?P<Janus>^janus\s*pub.*)',
        r'(?P<Jarrold>^jarrold\s*pub.*)',
        r'(?P<Jasper>^jasper\s*pub.*)',
        r'(?P<JewishUUU0020Chronicle>^jewish chronicle.*)',
        r'(?P<JewishUUU0020Courier>^jewish courier.*)',
        r'(?P<JewishUUU0020NewspaperUUU0020PublishersUUU0020Syndicate>^jewish newspaper publishers syndicate.*)',
        r'(?P<JoeUUU0027s>^joe\'*s\s*press.*)',
        r'(?P<JohnUUU0020Bell>^john bell.*)',
        r'(?P<JohnUUU0020Benjamins>^john\s*benjamins\s*pub.*)',
        r'(?P<JohnUUU0020Murray>^[0-9\,\-\.\s]*j(ohn)? murray.*)',
        r'(?P<JonathanUUU0020Hebner>^jon\s*atha\s*n\s*hebner.*)',
        r'(?P<JutaUUU003BMitchellUUU0020Beazley>^juta.*?mitchel*.*?beazley.*)',
        r'(?P<JUUU0020Benjamins>^j\s*benjamins\s*pub.*)',
        r'(?P<JUUU0020BUUU0020Metzler>^j[.\s]*b[.\s]*metzler.*)',
        r'(?P<JUUU0020Darby>^j[.\s]*darby.*)',
        r'(?P<JUUU0020deUUU0020Lange>^j[.\s]*de[.\s]*lange.*)',
        r'(?P<JUUU0020GUUU0020Miller>^j[.\s]*g[.\s]*miller.*)',
        r'(?P<JUUU0020JohnsonUUU002CUUU0020RUUU0020BaldwinUUU002CUUU0020HUUU0020LUUU0020Gardner>^J.*?\bjohnson.*?\br.*?\bbaldwin*?\bh*?\bl*?\bgardner.*)',
        r'(?P<JUUU0020MUUU0020Dent>^jm*[.\s]*m[.\s]*dent$)',
        r'(?P<JUUU0020MUUU0020DentUUU003BCoUUU002DoperativeUUU0020PermanentUUU0020BuildingUUU0020Society>^jm*[.\s]*m[.\s]*dent.*?co[\-\s]*op.*?perm.*?building.*?soc.*)',
        r'(?P<Kabet>^kabet\s*press.*)',
        r'(?P<Kardo>.*\bEldonejo.*?\bkardo.*)',
        r'(?P<Kaufmann>^kaufmann\s*pub.*)',
        r'(?P<KeganUUU0020PaulUUU002CUUU0020TrenchUUU002CUUU0020TrUUU00FCbner>^kegan.*?paul.*?trench.*?tr.bner.*)',
        r'(?P<Kennels>^kennels\s*press.*)',
        r'(?P<Kennikat>^kennikat\s*press.*)',
        r'(?P<KentishUUU0020Times>^kentish times.*)',
        r'(?P<KentUUU0020Messenger>.*\bkent messenger.*)',
        r'(?P<KentUUU0020RegionalUUU0020Newspapers>^kent regional news.*)',
        r'(?P<Kingsgate>^kingsgate\s*press.*)',
        r'(?P<Kingsport>^kingsport\s*press.*)',
        r'(?P<Kingswood>^kingswood\s*press.*)',
        r'(?P<Kiwi>^kiwi\s*pub.*)',
        r'(?P<KMUUU0020Media>^k[.\s]*m[.\s]*media.*)',
        r'(?P<Knickerbocker>^knickerbocker\s*press.*)',
        r'(?P<KosUUU0020Media>^k[.\s]*o[.\s]*s[.\s]*media.*)',
        r'(?P<Kraushar>^kraushar\s*press.*)',
        r'(?P<KwangUUU0020Hwa>^kwang hwa\s+.*)',
        r'(?P<KwaraUUU0020State>^kwara state.*)',
        r'(?P<Lafleur>^lafleur(?![a-z]).*)',
        r'(?P<LancashireUUU0020UUU0026UUU0020CheshireUUU0020CountyUUU0020Newspapers>^lancashire.*?\bcheshire.*?\bcount.*?\bnewsp.*)',
        r'(?P<Lancet>^lancet.*)',
        r'(?P<Langley>^langley\s*press.*)',
        r'(?P<Lanthorn>^lanthorn\s*press.*)',
        r'(?P<LaUUU0020More>^la\s*more\s*press.*)',
        r'(?P<Laverock>^laverock\s*press.*)',
        r'(?P<Legend>^legend\s+(p).*)',
        r'(?P<LEGENDAUUU002CUUU0020EuropeanUUU0020HumanitiesUUU0020ResearchUUU0020Centre>^legend.*?european.*?humanities.*)',
        r'(?P<LeicesterUUU0020Mercury>^leicester mercury.*)',
        r'(?P<LemUUU00E9ac>^Lem.ac$)',
        r'(?P<LeuvenUUU0020UniversityUUU0020Press>^leuven.*?uni.*)',
        r'(?P<Lexham>^lexham\s*press.*)',
        r'(?P<Liberties>^liberties(.*?\b(press|pub).*)?)',
        r'(?P<LibraryUUU0020AssociationUUU003BTUUU0020UUU0026UUU0020AUUU0020Constable>.*\blibrary\s*association.*?\bt.*?\ba.*?\bconstable.*)',
        r'(?P<LibraryUUU0020ofUUU0020Congress>.*\blibrary of congress.*)',
        r'(?P<LigetUUU0020MUUU0171helyUUU0020AlapUUU00EDtvUUU00E1ny>^liget.*?m.hely.*?alap.t?v.ny.*)',
        r'(?P<LightningUUU0020Source>^lightning.*?\bsource(.*?\b(australia|new\s*zealand|press|pub|south\s*africa).*)?)',
        r'(?P<Lion>^lion\s+.*)',
        r'(?P<Liquid>^liquid\s*press.*)',
        r'(?P<LittleUUU002CUUU0020Brown>^(boston )?little,*\s*(&|and)?\s*brown.*)',
        r'(?P<Liveright>^liveright.*)',
        r'(?P<LocalUUU0020World>^local world.*)',
        r'(?P<LocustUUU0020Hill>^locust\s*hill\s*press.*)',
        r'(?P<LondonUUU0020AcademyUUU0020ofUUU0020MusicUUU0020UUU0026UUU0020DramaticUUU0020Art>.*\blondon\s*academy.*?\bmusic.*?\bdramatic.*?\bart.*)',
        r'(?P<LondonUUU0020PrintingUUU0020UUU0026UUU0020Publishing>.*\blondon\s*printing.*?\bpublishing.*)',
        r'(?P<LondonUUU0020Stage>.*\bLondon Stage.*)',
        r'(?P<LongmansUUU0020Green>^longman.?s?[\,\s]*green$)',
        r'(?P<LongmanUUU003BBritishUUU0020Council>^longman.*?british.*?council.*)',
        r'(?P<Loot>^loot\s+.*)',
        r'(?P<Lothian>^lothian\s+.*)',
        r'(?P<Lotus>^lotus\s*pub.*)',
        r'(?P<Lovedale>^lovedale\s*press.*)',
        r'(?P<Lovell>^lovell\s+.*)',
        r'(?P<Ludo>^ludo\s*press.*)',
        r'(?P<Lulu>^lulu(.*?\b(com).*)?)',
        r'(?P<Lutterworth>^lutterworth\s*press.*)',
        r'(?P<LUUU0027u00C2geUUU0020dUUU0027Homme>.*\bge.*?homme$)',
        r'(?P<Lux>^lux\s*press.*)',
        r'(?P<Lyrebird>^lyrebird\s*press.*)',
        r'(?P<Macdonald>^mac\s*donald\s*&*\s*(ci?|children[\'s]*|e|education(al)?|general|guidelines|illustrated|young)*$)',
        r'(?P<MacdonaldUUU0020UUU0026UUU0020JaneUUU0027s>^mac\s*donald.*?jane.*)',
        r'(?P<MacdonaldUUU003BFutura>^mac\s*donald.*?futura.*)',
        r'(?P<MacdonaldUUU003BOptima>^mac\s*donald.*?optima.*)',
        r'(?P<MacdonaldUUU003BQueenUUU0020AnneUUU0020Press>^mac\s*donald.*?queen\s*anne.*)',
        r'(?P<MacLehose>^maclehose\s+.*)',
        r'(?P<MacLehoseUUU002CUUU0020Jackson>^(society\s*)?maclehose.*?jackson.*)',
        r'(?P<MacLehoseUUU003BUniversityUUU0020Press>^maclehose.*?uni.*)',
        r'(?P<Macmillan>^(western hemisphere by )?macmillan.*)',
        r'(?P<Madison>.*\bmadison\s*press.*)',
        r'(?P<Magna>^magna\b.*)',
        r'(?P<Magpie>^magpie\s*press.*)',
        r'(?P<MailUUU0020Newspapers>^mail\s*news.*)',
        r'(?P<MalcolmUUU0020House>^malcolm\s*house\s*pub.*)',
        r'(?P<MaloneUUU0020Society>^malone.*?society.*)',
        r'(?P<MaloneUUU0020SocietyUUU003BHUUU0020HartUUU003BOxfordUUU0020UniversityUUU0020Press>^malone.*?society.*?hart.*?oxford.*)',
        r'(?P<Maney>^maney(.*?\b(press|pub).*)?)',
        r'(?P<MannyUUU0020ManUUU0020Comics>^manny.*?man.*?comic.*)',
        r'(?P<ManorUUU0020House>^manor\s*house\s*press.*)',
        r'(?P<MansellUUU003BCassell>^mansel*.*?cassel*.*)',
        r'(?P<MarshallUUU0020Cavendish>^marshall.*?cavendish.*)',
        r'(?P<MaryUUU0020Glasgow>^mary.*?glasgow.*)',
        r'(?P<Mason>^mason\s*press.*)',
        r'(?P<MaxwellUUU0020Macmillan>^maxwell\s*ma?cmillan.*)',
        r'(?P<Maya>^maya\s+.*)',
        r'(?P<Mayflower>^mayflower\s*pub.*)',
        r'(?P<McGrawUUU002DHill>^mcgraw.*?hill.*)',
        r'(?P<Meador>^meador\s*pub.*)',
        r'(?P<MeadowUUU0020Geese>^meadow\s*geese\s*press.*)',
        r'(?P<MediciUUU0020SocietyUUU003BPhilipUUU0020LeeUUU0020Warner>^medici.*?society.*?phil*ip*.*?lee.*?warner.*)',
        r'(?P<Melchisedec>^melchisedec\s*press.*)',
        r'(?P<Mellen>^mellen\s*press.*)',
        r'(?P<MentionUUU0020theUUU0020War>^mention.*?\bthe.*?\bwar(.*?\b(press|pub).*)?)',
        r'(?P<MerchandUUU0020Lachhmandas>^merchand\s*lachhmandas\s*pub.*)',
        r'(?P<MerchantsUUU0020UUU0026UUU0020PlantersUUU0020Gazette>^merchant.*?planter.*?gaz.*)',
        r'(?P<MH>^mh\s*pub.*)',
        r'(?P<MichelUUU0020LUUU00e9vy>^michel.*?l.vy.*)',
        r'(?P<Micropress>^micropress\s+.*)',
        r'(?P<MidlandUUU0020WeeklyUUU0020Media>^midland weekly media.*)',
        r'(?P<MidUUU0020SomersetUUU0020Newspapers>^mid.*?\bsomerset.*?\bnews.*)',
        r'(?P<MillieUUU0020KramerUUU003BEUUU0020JUUU0020Arnold>^millie.*?kramer.*?e[.\s]*j[.\s]*arnold.*)',
        r'(?P<Mirror>^mirror\s*press.*)',
        r'(?P<MitchellUUU0020Beazley>^mitchel*.*?beazley.*)',
        r'(?P<Mitre>^mitre\s*press.*)',
        r'(?P<MonashUUU0020University>^monash\s*university\s*pub.*)',
        r'(?P<MonmouthshireUUU0020Beacon>.*\bmonmouthshire beacon.*)',
        r'(?P<Moray>^moray\b.*)',
        r'(?P<MorganUUU002DGrampian>^morgan.*?grampian.*)',
        r'(?P<Morija>^morija\s+.*)',
        r'(?P<Morland>^morland\s*press.*)',
        r'(?P<MorningUUU0020Star>^morning star\s+.*)',
        r'(?P<Morpheus>^morpheus.*)',
        r'(?P<Morse>^morse\s*press.*)',
        r'(?P<Mortimer>^mortimer\s+.*)',
        r'(?P<Morton>^morton\s+.*)',
        r'(?P<Mortons>^mortons\s+.*)',
        r'(?P<MoS>^mos\s*pub.*)',
        r'(?P<MSZMPUUU0020BUUU00e9kUUU00e9sUUU0020Megyei>^m[.\s]*s[.\s]*z[.\s]*m[.\s]*p[.\s]*b.k.s megyei.*)',
        r'(?P<MultimediaUUU0020International>^multimedia international.*)',
        r'(?P<MurrayUUU003BNuffieldUUU0020Foundation>^murray.*?nuffield\s*foundation.*)',
        r'(?P<MuseumUUU0020ofUUU0020LondonUUU0020ArchaeologyUUU0020Service>^museum.*?\bof.*?\blondon.*?\barchaeology.*)',
        r'(?P<MusicUUU0020ForUUU0020Strings>^m(usic|USIC).*?for.*?s(tring|TRING).*)',
        r'(?P<MUUU0020D>^m\s*d\s*pub.*)',
        r'(?P<Nassau>^nassau\s*press.*)',
        r'(?P<NathanielUUU0020Butter>^nathaniel.*?butter.*)',
        r'(?P<NationalUUU0020PortraitUUU0020Gallery>^national\s*portrait\s*gallery\s*pub.*)',
        r'(?P<NCJUUU0020Media>^n[.\s]*c[.\s]*j[.\s]*media.*)',
        r'(?P<NederlandscheUUU0020Boekhandel>^nederland.*?boekhandel.*)',
        r'(?P<NeneUUU0020ValleyUUU0020News>.*\bnene valley news.*)',
        r'(?P<NewburyUUU0020WeeklyUUU0020News>^newbury weekly news.*)',
        r'(?P<NewlynUUU0020Orion>^newlyn?\s*orion.*)',
        r'(?P<Newnes>^newnes\s+.*)',
        r'(?P<NewsplanUUU00202000>^newsplan 2000.*)',
        r'(?P<Newsquest>.*\bnewsquest.*)',
        r'(?P<NewUUU0020AmericanUUU0020Library>^new\s*american\s*library.*)',
        r'(?P<NewUUU0020Century>^new\s*century\s*press.*)',
        r'(?P<NewUUU0020Dawn>^new\s*dawn\s*press.*)',
        r'(?P<NewUUU0020EnglishUUU0020Library>^new\s*english\s*library.*)',
        r'(?P<NewUUU0020YorkUUU0020ReviewUUU0020ofUUU0020Books>.*\bnew york review (of )?books.*)',
        r'(?P<NicholasUUU0020Brealey>^nicholas\s*brealey.*)',
        r'(?P<NickUUU0020HernUUU003BRoyalUUU0020NationalUUU0020Theatre>^nick.*?hern.*?royal.*?national.*?theatre.*)',
        r'(?P<Nonesuch>^nonesuch\s*press.*)',
        r'(?P<Normal>^normal\s*press.*)',
        r'(?P<NorthamptonUUU0020Pioneer>.*\bnorthampton pioneer.*)',
        r'(?P<Northcliffe>^northcliffe.*)',
        r'(?P<NortheastUUU0020Press>^northea?st press.*)',
        r'(?P<NorthernUUU0020Star>^northern star.*)',
        r'(?P<NorthUUU0020DevonUUU0020JournalUUU002DHerald>^north.*?\bdevon.*?\bjournal.*?\bh.*)',
        r'(?P<NorthUUU0020LondonUUU0020Newspapers>^north london news.*)',
        r'(?P<NorthUUU0020Star>^north\s*star\s*press.*)',
        r'(?P<NorthUUU0020WalesUUU0020News>^north wales news.*)',
        r'(?P<NorthUUU0020WalesUUU0020WeeklyUUU0020News>^north wales weekly news.*)',
        r'(?P<NorthUUU0020WestUUU0020ofUUU0020IrelandUUU0020PrintingUUU0020UUU0026UUU0020PublishingUUU0020Company>^n(orth)?[.\s]*w(est)?[.\s]*(of)?\s*ireland\s*print.*)',
        r'(?P<NottinghamUUU0020Post>^nottingham post.*)',
        r'(?P<Novello>^novello.*)',
        r'(?P<NT>^nt\s*pub.*)',
        r'(?P<NWNUUU0020Media>^n[.\s]*w[.\s]*n[.\s]*media.*)',
        r'(?P<OakUUU0020Knoll>^oak\s*knoll\s*press.*)',
        r'(?P<OakUUU0020TreeUUU003BWardUUU0020Lock>^oak\s*tree.*?ward\s*lock.*)',
        r'(?P<Occult>^occult\s*pub.*)',
        r'(?P<Octopus>^octopus (p|book|illus).*)',
        r'(?P<Odhams>^odhams\s*press.*)',
        r'(?P<Odyssey>^odyssey\s*press.*)',
        r'(?P<Offaut>.*\boffaut\b.*)',
        r'(?P<OifigUUU0020anUUU0020tUUU002DSolUUU00E1thair>^oifig.*?sol.thair.*)',
        r'(?P<OldUUU0020Greek>^old\s*greek\s*press.*)',
        r'(?P<OldUUU0020Stile>^old\s*stile\s*press.*)',
        r'(?P<Oleander>^oleander\s*press.*)',
        r'(?P<OLMAUUU002DPress>^olma-*press\s*press.*)',
        r'(?P<Oneworld>^oneworld(.*?\b(press|pub).*)?)',
        r'(?P<Orbit>^orbit (bo?o?ks|pub|academic).*)',
        r'(?P<OrbitUUU003BSphere>^orbit sphere.*)',
        r'(?P<Orchard>^orchard (bo?o?ks|pub|academic).*)',
        r'(?P<OrchardUUU0020Gallery>^orchard gallery.*)',
        r'(?P<Orion>^orion\s*(audio|book|business|child|contempor|hard|p|\-*ver).*)',
        r'(?P<OrionUUU0020ChildrenUUU0027s>^orion\s*ch?ildren.*)',
        r'(?P<Ornament>^ornament\s*press.*)',
        r'(?P<OrphanUUU0020School>^orphan\s*school\s*press.*)',
        r'(?P<Orpheus>^o\s*r\s*pheus.*)',
        r'(?P<OrpheusUUU0020Music>^orpheus.*?music.*)',
        r'(?P<OrpheusUUU0020theUUU0020Pantomime>^orpheus.*?panto.*)',
        r'(?P<Orpheusz>.*\borpheusz.*)',
        r'(?P<Osprey>^osprey\s*pub.*)',
        r'(?P<Otakou>^otakou\s*press.*)',
        r'(?P<Overlook>^overlook\s*press.*)',
        r'(?P<Overture>^overture\s*pub.*)',
        r'(?P<Oxford>^oxford\s*press.*)',
        r'(?P<OxfordUUU0020Institute>^oxford\s*institute\s*press.*)',
        r'(?P<OxfordUUU0020UniversityUUU0020Press>^(^o[.\s]*u[.\s]*p[.\s]*|(u\.*(nited)?\s*s\.*(tates)?\s*o?f?\s*a\.*(merica)?\s*)?oxford\s*un?i?).*)',
        r'(?P<Paddington>^paddington\s*press.*)',
        r'(?P<Pageant>^pageant\s*press.*)',
        r'(?P<Pagnerre>^pagnerre.*)',
        r'(?P<PalgraveUUU0020Macmillan>^palgra[cv]e.*?\bmacmillan.*)',
        r'(?P<Paradine>^paradine\s*pub.*)',
        r'(?P<Paragon>^paragon\s*press.*)',
        r'(?P<Peak>^peak\s*press.*)',
        r'(?P<Peal>^peal\s*press.*)',
        r'(?P<Pearson>^pearson.*)',
        r'(?P<PearUUU0020Tree>^pear\s*tree\s*press.*)',
        r'(?P<Peebles>^peebles\s*press.*)',
        r'(?P<Pegasus>^pegasus\s*press.*)',
        r'(?P<Pen>^pen\s*press.*)',
        r'(?P<Penguin>^pengui?n.*)',
        r'(?P<PenguinUUU0020Putnam>^pengui?n\b.*?\bputnam.*)',
        r'(?P<Penn>^penn\s*pub.*)',
        r'(?P<Pennyroyal>^pennyroyal\s*press.*)',
        r'(?P<Pentland>^pentland\s*press.*)',
        r'(?P<Pergamon>^pergamon\s*press.*)',
        r'(?P<PeterUUU0020Pauper>^peter\s*pauper\s*press.*)',
        r'(?P<PeterUUU0020Robinson>^peter robinson p.*)',
        r'(?P<PhilippUUU0020Reclam>^p(hil*ip*)?.*?reclam.*)',
        r'(?P<Philips>^phil*i*p.?s(?! (and|&)).*)',
        r'(?P<PhilipUUU0020Allan>^phil*ip* al*an.*)',
        r'(?P<Phoenix>^phoenix\s*(book|educ|illus|map|p|pamph|poet|pub|verl).*)',
        r'(?P<PhoenixUUU0020Sports>^phoenix\s*sport.*)',
        r'(?P<Piatkus>^piatkus(?! Con).*)',
        r'(?P<PictorialUUU0020ChartsUUU0020EducationalUUU0020Trust>^pictorial.*?(charts|trust).*?educational.*?trust.*)',
        r'(?P<Pilgrim>^pilgrim\s*press.*)',
        r'(?P<Pinter>^pinter\s*(pub|ref).*)',
        r'(?P<Pioneer>^pioneer\s*press.*)',
        r'(?P<Pioneer>^pioneer\s*pub.*)',
        r'(?P<Pitkin>^pitkin(.*?\b(guide|press|pub).*)?)',
        r'(?P<PlanetUUU0020Three>^planet\s*three\s*pub.*)',
        r'(?P<Plantin>^plantin\s*press.*)',
        r'(?P<Playdead>^playdead\s*press.*)',
        r'(?P<Players>^players\s*press.*)',
        r'(?P<PlaywrightsUUU0020Canada>^playwrights\s*canada\s*press.*)',
        r'(?P<PlumeUUU003BWardUUU0020Lock>^plume.*?ward\s*lock.*)',
        r'(?P<Plutarch>^plutarch\s*press.*)',
        r'(?P<Pluto>^pluto p.*)',
        r'(?P<PoetUUU00F3wUUU0020iUUU0020Malarzy>.*\bpoet.w.*?malarzy.*)',
        r'(?P<Polity>^polity\s*press.*)',
        r'(?P<Poussielgue>^poussielgue.*)',
        r'(?P<Powell>^powell\s*pub.*)',
        r'(?P<Prairie>^prairie\s*press.*)',
        r'(?P<PremiUUU00E8resUUU0020Loges>^premi.res.*?loges.*)',
        r'(?P<PrenticeUUU0020Hall>^prentice.*?hall.*)',
        r'(?P<PressesUUU0020deUUU0020lUUU0027UniversitUUU00E9UUU0020ParisUUU002DSorbonne>^(PUPS|press.*?univ.*?paris.*?sorbonne).*)',
        r'(?P<Prestwick>^prestwick.*)',
        r'(?P<Preview>^preview\s*pub.*)',
        r'(?P<Pryor>^pryor\s*pub.*)',
        r'(?P<PubliBookUUU003BWriteSpace>^publibook.*?writespace.*)',
        r'(?P<Pula>^pula\s*press.*)',
        r'(?P<PurdueUUU0020University>^purdue.*?university.*)',
        r'(?P<Pushkin>^pushkin.*)',
        r'(?P<PutnamUUU003BCUUU0020CUUU0020JungUUU0020FoundationUUU0020forUUU0020AnalyticalUUU0020Psychology>^putnam.*?\bjung.*?\bfoundation.*?psychology.*)',
        r'(?P<PUUU0020Lang>^p\s*lang\s*pub.*)',
        r'(?P<pUUU0027sUUU0020UUU0026UUU0020qUUU0027s>^p\'*s\s*(&|and|et|und)\s*q\'*s\s*press.*)',
        r'(?P<Pyracantha>^pyracantha\s*press.*)',
        r'(?P<QED>^qed\s*pub.*)',
        r'(?P<Queensway>^queensway\s*press.*)',
        r'(?P<QueenUUU0020AnneUUU0020Press>^queen\s*anne\s*p*(ress)?$)',
        r'(?P<QuelleUUU0020UUU0026UUU0020Meyer>^quelle.*?m[ae]yer.*)',
        r'(?P<Quercus>^quercus(?! eight).*)',
        r'(?P<Quest>^quest(?![\-]).*)',
        r'(?P<QuicksilverUUU0020Times>^quicksilver times.*)',
        r'(?P<Rabenpresse>^(verlag\s*)?(die\s*)?rabenpresse.*)',
        r'(?P<RandomUUU0020House>^random house.*)',
        r'(?P<Raven>^raven\s*press.*)',
        r'(?P<ReadersUUU0020Union>.*\breader.*?\bunion.*)',
        r'(?P<ReadersUUU0020UnionUUU003BConstable>.*\breader.*?union.*?constable.*)',
        r'(?P<Real>^real\s*press.*)',
        r'(?P<Redpath>^redpath\s*press.*)',
        r'(?P<ReedUUU0020Midland>^reed midland.*)',
        r'(?P<Regency>^regency\s*press.*)',
        r'(?P<Richards>^richards\s*press.*)',
        r'(?P<RisingUUU0020Stars>^rising stars.*)',
        r'(?P<Riverside>^riverside\s*press.*)',
        r'(?P<Roberton>^roberton\s*pub.*)',
        r'(?P<RobertUUU0020Maclehose>^r(obert?)?.*?\bmaclehose.*)',
        r'(?P<RobertUUU0020MaclehoseUUU003BUniversityUUU0020Press>^r(obert?)?.*?\bmaclehose.*?\buni.*)',
        r'(?P<RobUUU0020Roy>^rob\s*roy\s*press.*)',
        r'(?P<RockportUUU003BCassell>^rockport.*?cassel*.*)',
        r'(?P<Roman>^roman$)',
        r'(?P<Ronsdale>^ronsdale\s*press.*)',
        r'(?P<RoundUUU0020Table>^round\s*table\s*press.*)',
        r'(?P<Routledge>^routledge\s*pub.*)',
        r'(?P<RowmanUUU0020UUU0026UUU0020Littlefield>^rowman.*?littlefield.*)',
        r'(?P<Rowohlt>^rowohlt.*)',
        r'(?P<Roxburghe>^roxburghe\s*press.*)',
        r'(?P<RoyalUUU0020AcademyUUU0020ofUUU0020Arts>^royal academy of arts.*)',
        r'(?P<RoyalUUU0020ItalianUUU0020Opera>^royal.*?italian.*?opera.*)',
        r'(?P<RSC>^rsc\s*pub.*)',
        r'(?P<RudolfUUU0020Steiner>^rudolf\s*steiner\s*press.*)',
        r'(?P<Rumney>^rumney\s*pub.*)',
        r'(?P<Running>^running\s*press.*)',
        r'(?P<RupertUUU0020HartUUU002DDavis>^rupert.*?hart.*?davie?s.*)',
        r'(?P<Ruthvens>^ruthvens.*)',
        r'(?P<Rutland>^rutland\s*pub.*)',
        r'(?P<RUUU0020vonUUU0020Grumbkow>^r.*?grumbkow.*)',
        r'(?P<Rydal>^rydal\s*press.*)',
        r'(?P<Rydon>^rydon\s*pub.*)',
        r'(?P<Ryerson>^ryerson\s*press.*)',
        r'(?P<SaintUUU0020Austin>^saint\s*austin\s*press.*)',
        r'(?P<SaintUUU0020Catherine>^saint\s*catherine\s*press.*)',
        r'(?P<Salem>^salem\s*press.*)',
        r'(?P<SalisburyUUU0020Journal>^salisbury journal.*)',
        r'(?P<Saltyard>^saltyard.*)',
        r'(?P<SampsonUUU0020Low>^sampson.*?\blow.*)',
        r'(?P<SampsonUUU0020LowUUU0020UUU0026UUU0020Marston>^sampson.*?\blow.*?\bmarston.*)',
        r'(?P<Samuel>^samuel\s*press.*)',
        r'(?P<SamuelsUUU002DBacon>^samuels-*bacon\s*pub.*)',
        r'(?P<Sargent>^sargent\s*pub.*)',
        r'(?P<Saturn>^saturn\s*press.*)',
        r'(?P<Satyabadi>^satyabadi\s*press.*)',
        r'(?P<Saudamini>^saudamini\s*press.*)',
        r'(?P<Scarecrow>^scarecrow\s*press.*)',
        r'(?P<Sceptre>^(septre sic.*?)?sceptre.*)',
        r'(?P<SceptreUUU003BMenard>^sceptre.*?menard.*)',
        r'(?P<Scholastic>^scholastic(.*?\b(australia|new\s*zealand|press|pub|south\s*africa).*)?)',
        r'(?P<School>^school\s*press.*)',
        r'(?P<Scolar>^scolar\s*press.*)',
        r'(?P<ScottishUUU0020Media>^scottish media.*)',
        r'(?P<ScottishUUU0020UUU0026UUU0020Universal>^scottish (&|and) universal.*)',
        r'(?P<ScottUUU0020Foresman>^scott,*\s*foresman.*)',
        r'(?P<Scribo>^scribo(?![a-z]).*)',
        r'(?P<Seabury>^seabury\s*press.*)',
        r'(?P<SelfMadeHero>^self.*?made.*?hero.*)',
        r'(?P<SevernUUU0020House>^severn.*?house.*)',
        r'(?P<Shakespeare>^shakespeare\s*press.*)',
        r'(?P<ShakespeareUUU0020BirthplaceUUU0020Trust>^shakespeare.*?birthplace.*?trust.*)',
        r'(?P<ShakespeareUUU0020BirthplaceUUU0020TrustUUU003BDugdaleUUU0020Society>^shakespeare.*?birthplace.*?dugdale.*)',
        r'(?P<ShakespeareUUU0020Head>^shakespeare\s*head\s*press.*)',
        r'(?P<ShakespeareUUU0020LibraryUUU002CUUU0020FudanUUU0020University>^shakespeare.*?library.*?fudan.*)',
        r'(?P<ShakespeareUUU0020MemorialUUU0020Theatre>^shakespeare.*?memorial.*)',
        r'(?P<ShakespeareUUU0020SocietyUUU0020ofUUU0020NewUUU0020SouthUUU0020Wales>^shakespeare.*?society.*?\bn[\.\s]*s[\.\s]*w.*)',
        r'(?P<ShakespeareUUU0020SocietyUUU003BAvantgarde>^shakespeare.*?society.*?avantgarde.*)',
        r'(?P<Shanway>^shanway\s*press.*)',
        r'(?P<Sharada>^sharada\s*pub.*)',
        r'(?P<SheepUUU0020Meadow>^sheep\s*meadow\s*press.*)',
        r'(?P<Sheldon>^sheldon\s*press.*)',
        r'(?P<ShepheardUUU002DWalwyn>^shepheard[\s\-]*walw?yn.*)',
        r'(?P<ShinozakiUUU0020Shorin>^shinozaki[\s\-]*shorin.*)',
        r'(?P<Shoestring>^shoestring\s*press.*)',
        r'(?P<ShoeUUU0020String>^shoe\s*string\s*press.*)',
        r'(?P<SimonUUU0020King>^simon\s*king\s*press.*)',
        r'(?P<SimonUUU0020UUU0026UUU0020Schuster>^simon.*?schuster.*)',
        r'(?P<SimpkinUUU002CUUU0020Marshall>^simpkin.*?marshall.*)',
        r'(?P<SindhiUUU0020Sahit>^sindhi\s*sahit\s*pub.*)',
        r'(?P<SirUUU0020IsaacUUU0020Pitman>^sir.*?\bi.*?\bpitman.*)',
        r'(?P<SkeltonUUU0020Robinson>^skelton\s*robinson.*)',
        r'(?P<Skyhorse>^skyhorse\s*pub.*)',
        r'(?P<SloughUUU0020UUU0026UUU0020WindsorUUU0020Express>^slough (&|and) windsor express.*)',
        r'(?P<Slovenskaknjica>^slovenskaknjica.*)',
        r'(?P<Small>^small\s*press.*)',
        r'(?P<Smith>^smith\s*press.*)',
        r'(?P<SmithUUU002CUUU0020Elder>^(philadelphia\s*)?smith,*\s*elder*$)',
        r'(?P<Sonatun>^sonatun\s*press.*)',
        r'(?P<SonoUUU0020Nis>^sono\s*nis\s*press.*)',
        r'(?P<SouthUUU0020LincolnshireUUU0020Target>^south linc(olnshire)?s? target.*)',
        r'(?P<SouthUUU0020ManchesterUUU0020Reporter>^south m(an)?/?c(heste)?r r?eporter.*)',
        r'(?P<SouthUUU0020WalesUUU0020Echo>^south wales echo.*)',
        r'(?P<Souvenir>^souvenir\s*press.*)',
        r'(?P<Soybean>^soybean\s*press.*)',
        r'(?P<Spark>^spark\s*pub.*)',
        r'(?P<SparkNotes>^spark\s*notes.*)',
        r'(?P<Sphere>^sphere\s*(pub|ref|study).*)',
        r'(?P<Spottiswoode>^spott?iswoo?de.*)',
        r'(?P<Springer>^springer(\s*-*verlag.*)?)',
        r'(?P<StadtbUUU00FCcherei>^stadtb.cherei.*)',
        r'(?P<StaffordshireUUU0020Sentinel>^staffordshire sentin(e|a)l.*)',
        r'(?P<StainerUUU0020UUU0026UUU0020Bell>^stainer.*?bell.*)',
        r'(?P<StanbrookUUU0020Abbey>^stanbrook\s*abbey\s*press.*)',
        r'(?P<Staples>^staples\s*press.*)',
        r'(?P<SteadUUU0027s>^stead\'*s\s*pub.*)',
        r'(?P<StepUUU0020Beach>^step.*?\bbeach(.*?\b(press|pub).*)?)',
        r'(?P<Sterling>^sterling.*)',
        r'(?P<SteveUUU0020Gooch>^steve\s*gooch\s*pub.*)',
        r'(?P<Stonecrop>^stonecrop\s*pub.*)',
        r'(?P<Stratford>^stratford\s*press.*)',
        r'(?P<StratfordUUU002DuponUUU002DAvon>^stratford-*upon-*avon\s*press.*)',
        r'(?P<Strauss>^strauss\s*(edition\s*wien)?$)',
        r'(?P<StUUU0020JosephUUU0027sUUU0020College>^st\s*joseph\'*s\s*college\s*press.*)',
        r'(?P<StUUU0020JosephUUU0027sUUU0020Institute>^st\s*joseph\'*s\s*institute\s*press.*)',
        r'(?P<StUUU0020MartinUUU0027s>^(Canada by )?st[\.\s]*martin.*)',
        r'(?P<Suburban>^suburban\s*press.*)',
        r'(?P<Sucre>^(editorial\s*)?sucre$)',
        r'(?P<SundayUUU0020TimesUUU003BNationalUUU0020PortraitUUU0020Gallery>^sunday\s*times.*?national\s*portrait\s*gallery.*)',
        r'(?P<SUNY>^suny\s*press.*)',
        r'(?P<SurreyUUU0020UUU0026UUU0020HantsUUU0020Newspapers>^surrey (&|and) hants news.*)',
        r'(?P<Sutton>^sutton\s*pub.*)',
        r'(?P<Swallow>^swallow\s*press.*)',
        r'(?P<SweetUUU0020Cherry>^sweet\s*cherry\s*pub.*)',
        r'(?P<Swift>^swift\s*pub.*)',
        r'(?P<Sylvan>^sylvan.*)',
        r'(?P<Symposium>^symposium\s*pub.*)',
        r'(?P<Tafelberg>^tafelberg.*)',
        r'(?P<TalmyUUU0020Franklin>^talm?n?e?y.*?franklin.*)',
        r'(?P<TalusUUU0020dUUU0027approche>^talus.*?approche.*)',
        r'(?P<Taplinger>^taplinger\s*pub.*)',
        r'(?P<Tavistock>^tavistock\s*pub.*)',
        r'(?P<TeacherUUU0020Ideas>^teacher\s*ideas\s*press.*)',
        r'(?P<TeachUUU0020YourselfUUU003BHodderUUU0020UUU0026UUU0020Stoughton>^teach.*?yourself.*?hodd[e ]r\s*(&|an?d)?\s*s[tl]*r?o?[u ][gh]*[ty ]*n?o?[nm]?.*)',
        r'(?P<Tenny>^tenny\s*press.*)',
        r'(?P<Tern>^tern\s*press.*)',
        r'(?P<TexasUUU0020Tech>^texas\s*tech\s*press.*)',
        r'(?P<TexasUUU0020Western>^texas\s*western\s*press.*)',
        r'(?P<Thames>^thames\s*pub.*)',
        r'(?P<ThamesUUU0020UUU0026UUU0020Hudson>^thames.*?hudson.*)',
        r'(?P<Theodore>^theodore\s*press.*)',
        r'(?P<Theosophical>^theosophical\s*press.*)',
        r'(?P<Thoemmes>^thoemmes\s*press.*)',
        r'(?P<ThomasUUU0020AnnanUUU003BJamesUUU0020MaclehoseUUU003BUniversityUUU0020Press>^thomas annan.*j(ames)?.*?maclehose.*?uni.*)',
        r'(?P<ThomasUUU0020CockingUUU0020inUUU0020SmallUUU002DStreet>^thomas cocking in small.*)',
        r'(?P<ThomasUUU0020Gibson>^thomas gibson\s*pub.*)',
        r'(?P<ThomasUUU0020KinnerslyUUU0020inUUU0020StUUU0020PaulUUU0027sUUU0020churchUUU002Dyard>^thomas kinnersly in s(ain)?t\.? paul.*)',
        r'(?P<ThomasUUU0020Miller>^thomas miller.*)',
        r'(?P<ThorntonUUU0020WUUU0020BurgessUUU0020MuseumUUU003BGreenUUU0020BriarUUU0020NatureUUU0020Center>^thornton.*?burgess.*?green briar.*)',
        r'(?P<ThreeUUU0020Kings>^three\s*kings\s*press.*)',
        r'(?P<TimberUUU0020Frame>^timber\s*frame\s*pub.*)',
        r'(?P<Times>^times.*(p).*)',
        r'(?P<TimesUUU003BAnthonyUUU0020GibbsUUU0020UUU0026UUU0020Phillips>^times.*?gibbs.*?phil*i*p.*)',
        r'(?P<TimeUUU0020Warner>^time\s*warner\s*(int|paper).*)',
        r'(?P<TindallUUU0020UUU0026UUU0020Cassell>^(re,?\s*)?tindal*.*?cassel*.*)',
        r'(?P<Tinderbox>^tinderbox.*)',
        r'(?P<TipperaryUUU0020PrintingUUU0020UUU0026UUU0020PublishingUUU0020Company>^tipperary print.*)',
        r'(?P<TonsonStrand>.*\btonson.*?strand.*)',
        r'(?P<TonsonUUU003BSUUU0020Draper>.*\btonson.*?\bs[\.\s]*draper.*)',
        r'(?P<TonsonUUU003BSUUU0020DraperUUU003BRUUU0020WellingtonUUU003BEUUU0020New>.*\btonson.*?\bdraper.*?\bwellington.*?\bnew.*)',
        r'(?P<Torch>^torch\s*press.*)',
        r'(?P<Tower>^tower\s*press.*)',
        r'(?P<TrajectumUUU0020adUUU0020Mosam>^trajectum\s*ad\s*mosam\s*press.*)',
        r'(?P<Transatlantic>^transatlantic\s*press.*)',
        r'(?P<Treasure>^treasure\s*press.*)',
        r'(?P<Tribune>^tribune\s*pub.*)',
        r'(?P<TrinityUUU0020Mirror>.*\btrinity mirror.*)',
        r'(?P<Troubador>^troubador(.*?\b(press|pub).*)?)',
        r'(?P<TrUUU00FCbner>.*\btr.bner.*)',
        r'(?P<TrUUU00FCbnerUUU003BNewUUU0020ShakspereUUU0020Society>.*\b(tr.bner.*?new.*?shakespeare|new.*?shakespeare.*?tr.bner).*)',
        r'(?P<Turnaround>.*\bturnaround.*)',
        r'(?P<TUUU0020Davies>^[0-9\.\,\-\s]*T\s*Davies$)',
        r'(?P<TUUU0020Presser>^t[.\s]*presser.*)',
        r'(?P<TUUU0020UUU0026UUU0020AUUU0020ConstableUUU003BEdinburghUUU0020UniversityUUU0020Press>^\bt.*?\ba.*?\bconstable.*?\buniversity.*)',
        r'(?P<TUUU0020UUU0026UUU0020WUUU0020LowndesUUU003BWUUU0020NicollUUU003BSUUU0020Bladon>.*\bt.*?\bw.*?\blowndes.*?\bw.*?\bnicoll.*?\bs.*?\bbladon.*)',
        r'(?P<TwoUUU002DCan>^two[\s\-]*can$)',
        r'(?P<TwoUUU0020Rivers>^two.*?\brivers(.*?\b(press|pub).*)?)',
        r'(?P<Tynron>^tynron\s*press.*)',
        r'(?P<Ukkaz>^ukkaz.*)',
        r'(?P<UMIUUU0020Research>^umi\s*research\s*press.*)',
        r'(?P<UnionUUU0020ofUUU0020MuslimUUU0020Organisations>^union\s*of\s*muslim\s*organi[sz]ations.*)',
        r'(?P<Unisa>^unisa\s*press.*)',
        r'(?P<United>^united\s*press.*)',
        r'(?P<UnitedUUU0020KingdomUUU0020AtomicUUU0020EnergyUUU0020Authority>^(UKAEA$|(atomic energy (research )?establishment|u(nited)?\s*k(ingdom)? atomic energy|UKA?EA.*?(atomic|culcheth|fusion|harwell|winfrith)).*))',
        r'(?P<UnitedUUU0020KingdomUUU0020ReadingUUU0020Association>^u(nited)?[.\s]*k(ingdom)?.*?reading.*)',
        r'(?P<UniversityUUU0020Press>^univer[.\s]*press\s*$)',
        r'(?P<UniversalUUU0020Communications>^universal communication.*)',
        r'(?P<UniversalUUU002DEdition>^universal[\s\-]*edition.*)',
        r'(?P<UniversityUUU0020LibraryUUU003BArtUUU0020GalleryUUU0020ofUUU0020OntarioUUU003BMiller>^univers.*?librar.*?gallery.*?ontario.*?miller.*)',
        r'(?P<UniversityUUU0020ofUUU0020Kansas>^university\s*of\s*kansas\s*pub.*)',
        r'(?P<UniversityUUU0020ofUUU0020LeedsUUU003BEUUU0020JUUU0020Arnold>^uni.*?leeds.*?e[.\s]*j[.\s]*arnold.*)',
        r'(?P<UniversityUUU0020ofUUU0020LondonUUU0020InstituteUUU0020ofUUU0020HistoricalUUU0020Research>^university.*?london.*?historical.*?res.*)',
        r'(?P<UniversityUUU0020ofUUU0020LondonUUU0020Press>^university.*?lond.*)',
        r'(?P<UniversityUUU0020PressesUUU0020Marketing>^university.*?press\s*es.*?marketing.*)',
        r'(?P<UniversityUUU0020PressUUU0020ofUUU0020Colorado>^u(ni)?(versity)?\s*pr(ess)?\s*(of)?\s*colorado.*)',
        r'(?P<Urbane>^urbane\s*pub.*)',
        r'(?P<Usborne>^usborne\s*pub.*)',
        r'(?P<UtopiaUUU003BPercyUUU0020Miller>^utopia.*?percy\s*miller.*)',
        r'(?P<UtUUU0020Orpheus>^ut.*?orpheus.*)',
        r'(?P<UUU00C9ditionsUUU0020ThUUU00E9UUU00E2trales>^.ditions.*?th..trales.*)',
        r'(?P<UUU00D6sterreichischeUUU0020StudiengesellschaftUUU0020fUUU00FCrUUU0020Atomenergie>^.*?sterreich.*?studienge.*?atomenergie.*)',
        r'(?P<UWA>^uwa\s*pub.*)',
        r'(?P<Vantage>^vantage\s*press.*)',
        r'(?P<VanUUU0020deUUU0020SandtUUU0020deUUU0020Villiers>^van de sandt de villiers.*)',
        r'(?P<Vasanta>^vasanta\s*press.*)',
        r'(?P<VeeTeeAy>^vee\s*tee\s*ay.*)',
        r'(?P<Velluminous>^velluminous\s*press.*)',
        r'(?P<VerlagUUU0020derUUU0020GesellschaftUUU0020zurUUU0020FUUU00f6rderungUUU0020derUUU0020SystematischeUUU0020Musicwissenschaft>.*\bgesellschaft.*?forderung.*?system.*?musicwissenschaft.*)',
        r'(?P<VerlagUUU0020fUUU00fcrUUU0020Gesellschaftskritik>.*\bverlag.*?gesellschaftskritik.*)',
        r'(?P<VerlagUUU0020fUUU00fcrUUU0020SystematischeUUU0020Musicwissenschaft>.*\bsystem.*?musicwissenschaft.*)',
        r'(?P<VictorUUU0020Gollancz>^v(ic?r?tor)?\.?\s*gollancz.*)',
        r'(?P<Vidya>^vidya\s*pub.*)',
        r'(?P<VidyaUUU0020VilUUU0101sum>^vidya\s*vil.sum\s*press.*)',
        r'(?P<ViewUUU0020From>^view from( pub.*|$))',
        r'(?P<Virago>^virago.*)',
        r'(?P<Vision>^vision\s*press.*)',
        r'(?P<VUUU0101ni>^v.ni\s*press.*)',
        r'(?P<Wadsworth>^wadsworth.*)',
        r'(?P<Waiteata>^waiteata\s*press.*)',
        r'(?P<Wakefield>^wakefield\s*press.*)',
        r'(?P<Wallstein>^wallstein.*)',
        r'(?P<WallUUU0020StreetUUU0020Journal>^wall st(reet)?\.* j.*)',
        r'(?P<WaltonUUU0020Music>^walton\s*music.*)',
        r'(?P<WaltUUU0020Disney>^walt\s*disney.*)',
        r'(?P<WardUUU0020Lock>^([0-9]+\s*)?ward\s*lock.*)',
        r'(?P<WardUUU0020LockUUU003BBowden>^ward\s*lock.*?bowden.*)',
        r'(?P<WardUUU0020LockUUU003BTyler>^ward\s*lock.*?tyler.*)',
        r'(?P<Warner>^warner.*)',
        r'(?P<WarrenUUU0020UUU0026UUU0020Phillips>^warren.*?phil*ips?$)',
        r'(?P<WashingtonUUU0020Square>^washington\s*square\s*press.*)',
        r'(?P<Waterloo>^waterloo\s*press.*)',
        r'(?P<Watts>^watts (pub|book).*)',
        r'(?P<WattsUUU0020UUU0026UUU0020Bridgewater>^watts.*bridgewater.*)',
        r'(?P<WattsUUU002CUUU0020BlakeUUU002CUUU0020BearneUUU0020UUU0026UUU0020Company>^watts.*blake.*?bearne.*)',
        r'(?P<WattsUUU002CUUU0020HardyUUU0020UUU0026UUU0020Company>^watts.*hardy.*)',
        r'(?P<Wayland>^wayland.*)',
        r'(?P<WaylandUUU0020PartnershipUUU0020DevelopmentUUU0020Trust>^wayland\s*partnership\s*development\s*trust.*)',
        r'(?P<WBUUU0020Frampton>^w[.\s]*b[.\s]*frampton.*)',
        r'(?P<WeidenfeldUUU0020UUU0026UUU0020Nicolson>^(london\s*)?w[ei]*n?[d\s]*[e\s]*n?[f\s]*eld\s*(&|and)\s*nic?h?olso?n?(?!\s*(for |in )).*)',
        r'(?P<WeightUUU0020Watchers>^weight[\-\s]*watchers.*)',
        r'(?P<WelshUUU0020DevelopmentUUU0020AgencyUUU003BGatewayUUU0020Europe>^(welsh development agency.*?gateway europe|gateway europe.*?welsh development agency).*)',
        r'(?P<West>^west\s*pub.*)',
        r'(?P<Westerleigh>^westerleigh\s*pub.*)',
        r'(?P<WesternUUU0020Gazette>^western gazette.*)',
        r'(?P<WesternUUU0020MorningUUU0020News>^western morning news.*)',
        r'(?P<WesternUUU0020UUU0026UUU0020SouthUUU0020UUU0026UUU0020WestUUU0020WalesUUU0020AutoUUU0020Trader>^western\s*(&|and)?\s*s?(outh)?\s*(&|and)?\s*w?(est)?\s*wales\s*auto.*)',
        r'(?P<Westholm>^westholm\s*pub.*)',
        r'(?P<Westminster>^westminster\s*press.*)',
        r'(?P<WestUUU0020Coast>^west coast\s+.*)',
        r'(?P<WestUUU0020HighlandUUU0020PublishingUUU0020Company>^west highland pub.*)',
        r'(?P<WhatUUU0020onUUU0020Earth>^what\s*on\s*earth\s*pub.*)',
        r'(?P<WhiteUUU0020BurkettUUU0020MillerUUU0020CenterUUU0020ofUUU0020PublicUUU0020Affairs>^white\s*burh?k?ett\s*miller.*)',
        r'(?P<WHUUU0020Smith>^w[.\s]*h[.\s]*smith.*)',
        r'(?P<Wiley>^wiley\s*pub.*)',
        r'(?P<WileyUUU002DBlackwell>^wiley-.*?blackwell(.*?\b(press|pub).*)?)',
        r'(?P<WilfredUUU0020Edmunds>^wilfred edmunds.*)',
        r'(?P<WilfredUUU0020FUUU0020Elliot>^wilfred\s*f[.\s]*elliot.*)',
        r'(?P<WilliamUUU0020LaneUUU002CUUU0020atUUU0020theUUU0020MinervaUUU0020OfficeUUU002CUUU0020LeadenhallUUU0020Street>^william lane.*?minerva.*)',
        r'(?P<WilliamUUU0020Miller>.*\bw(ill?i?ia)?m miller$)',
        r'(?P<WilliamUUU0020MillerUUU002CUUU0020AlbemarleUUU0020Street>.*\bwil*i*am miller.*?alber*marle.*)',
        r'(?P<WilliamUUU0020Nicholson>^w(illia)?m? nicholson.*)',
        r'(?P<WilliamUUU0020NicholsonUUU003BAlbionUUU0020Works>^w(illia)?m? nicholson.*?albion.*)',
        r'(?P<WilliamUUU0020NicollUUU0020inUUU0020StUUU0020PaulUUU0027sUUU0020churchUUU002Dyard>^william nicoll in s(ain)?t\.? paul.*)',
        r'(?P<WilliamUUU0020Street>^william\s*street\s*press.*)',
        r'(?P<WilsonUUU0020UUU0026UUU0020Phillips>^wilson.*?phil*ips*$)',
        r'(?P<WiltonUUU0020Circle>^wilton\s*circle\s*press.*)',
        r'(?P<WiltshireUUU0020Times>^wiltshire times.*)',
        r'(?P<Winchester>^winchester\s*pub.*)',
        r'(?P<Winona>^winona\s*pub.*)',
        r'(?P<WirralUUU0020Newspapers>^wirral news.*)',
        r'(?P<Wise>^wise\s*pub.*)',
        r'(?P<WissenschaftlicherUUU0020VerlagUUU0020Trier>^(WVT|Wissenschaftlicher Verlag Trier).*)',
        r'(?P<Witherby>^witherby[\'s]*pub.*)',
        r'(?P<WomanUUU0027sUUU0020Play>^woman\'*s\s*play\s*press.*)',
        r'(?P<WomenUUU0027s>^women\'*s\s*press.*)',
        r'(?P<Woodlines>^woodlines\s*pub.*)',
        r'(?P<WorldUUU0020Film>^world\s*film\s*pub.*)',
        r'(?P<WorldUUU0020WildlifeUUU0020Fund>^(w\s*wildlife\s*fund|W[.\s]*W[.\s]*F\.* ).*)',
        r'(?P<WUUU0020AshUUU002CUUU0020LittleUUU0020TowerUUU0020Street>^w\s*ash.*?little.*?tower.*)',
        r'(?P<WUUU0020AshUUU002CUUU0020LittleUUU0020TowerUUU0020StreetUUU003BLUUU0020Wayland>^w\s*ash.*?little.*?tower.*?l\s*Wayland.*)',
        r'(?P<WUUU0020Clarke>^[0-9\.\,\-\s]*W\s*Clarke$)',
        r'(?P<WUUU0020HUUU0020RobinsonUUU003BWalsallUUU0020Press>^w[.\s]*h[.\s]*robinson.*?walsall.*)',
        r'(?P<WUUU0020LewisUUU003BRichardUUU0020Phillips>^w\s*lewis.*?richard\s*phil*ip.*)',
        r'(?P<WUUU0020MillerUUU002CUUU0020OldUUU0020BondUUU0020Street>^w\s*miller.*?old.*?bond.*)',
        r'(?P<WUUU0020PhillipsUUU003BSamuelUUU0020Curtis>^w\s*phil*ip.*?samuel\s*curtis.*)',
        r'(?P<WUUU0020Savage>^w[.\s]*savage.*)',
        r'(?P<Wykeham>^wykeham\s*press.*)',
        r'(?P<XLibris>^xlibris.*)',
        r'(?P<Yamashina>^yamashina\s*press.*)',
        r'(?P<YellowUUU0020Kite>^yellow\s*kite.*)',
        r'(?P<Yen>^yen\s*press.*)',
        r'(?P<York>^york\s*press.*)',
        r'(?P<YoungUUU0020Gaia>^young\s*gaia.*)',
        r'(?P<Yushodo>^yushodo\s*press.*)',
        r'(?P<Zoilus>^zoilus\s*press.*)',
        r'(?P<Zondervan>^zondervan.*)',
        )
